// Public brand expression derived from the supplied platform; no commercial guarantees.
import {taskScenes} from './task-visuals.mjs';
export const trajectoryMark=`<svg viewBox="0 0 56 48" fill="none" aria-hidden="true"><path d="M5 38h10V26h10" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-dasharray="3 5"/><path d="M24 26c13 0 5-17 22-17h5M44 3l7 6-7 6" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
export const brandLogo=`<a href="/" class="brand" aria-label="100 Pilot, accueil">${trajectoryMark}<span>100pilot<span class="brand-ai">.ai</span></span></a>`;
export const personas=[
 {id:'direction',pageId:'B001',url:'/pour-votre-equipe/dirigeant-pme/',label:'Je dirige une PME',role:'Dirigeant de PME',short:'Faire avancer l’entreprise sans tout reprendre à la main.',title:'Votre équipe a besoin de temps pour faire son métier.',intro:'Les factures arrivent par email, les échéances sont suivies dans un tableau et chacun cherche les pièces dont il a besoin. Nous prenons en charge une première tâche récurrente pour alléger ce travail de préparation.',scene:'admin',friction:'Vos équipes passent du temps à ranger les pièces et à retrouver ce qui manque.',gain:'Les documents sont réunis dans les dossiers convenus. L’équipe se concentre sur les exceptions et les décisions.',tasks:['P040','P041','P047','P051'],service:'P017',caseId:'P078',caseText:'Un audit B2B illustre le travail de diagnostic et de priorisation, avant toute correction.',keeps:'Votre responsable confirme les pièces incertaines, les paiements et les engagements de l’entreprise.',first:'Prenez une tâche qui revient chaque semaine et quelques exemples anonymisés. Nous regarderons les données disponibles, le temps de préparation et ce qui doit rester à l’équipe.',measure:'Comparez le temps de classement et de recherche sur un même type de dossier. Le temps de vérification des exceptions compte aussi.',titleMeta:'Automatisation pour les dirigeants de PME | 100 Pilot',description:'Factures, échéances et dossiers : automatisez une première tâche répétitive avec 100 Pilot et gardez la main sur les décisions de votre PME.'},
 {id:'commercial',pageId:'B002',url:'/pour-votre-equipe/responsable-commercial/',label:'Je développe les ventes',role:'Responsable commercial',short:'Préparer les contacts pour consacrer plus de temps aux échanges.',title:'Vos commerciaux ont mieux à faire que chercher chaque contact.',intro:'Avant le premier appel, votre équipe cherche les entreprises, vérifie les coordonnées et complète les fiches. Nous préparons cette base selon votre offre pour que les échanges puissent commencer avec un contexte.',scene:'commercial',friction:'La campagne attend que les commerciaux aient fini leurs recherches et recopié les informations.',gain:'Une liste d’entreprises sélectionnées avec les critères et les informations disponibles sert de point de départ à la campagne.',tasks:['P036','P035','P037','P038','P039','P043'],service:'P015',caseId:'P054',caseText:'Un distributeur B2B dispose d’un tableau de prospects préparé pour la qualification commerciale. Aucun résultat de vente n’est attribué à ce fichier.',keeps:'Le commercial choisit qui contacter, confirme le besoin et décide du message. Une entreprise sélectionnée n’est pas un client prêt à acheter.',first:'Montrez-nous votre offre, un segment de clients et un exemple de fiche exploitable. Le premier test porte sur une liste courte et des critères que votre équipe peut vérifier.',measure:'Comparez le temps nécessaire pour préparer un contact utilisable. Suivez séparément les rendez-vous et ventes, qui dépendent aussi des échanges commerciaux.',titleMeta:'Automatisation pour les équipes commerciales B2B | 100 Pilot',description:'Préparez les listes de prospects et les fiches CRM avec 100 Pilot. Vos commerciaux disposent du contexte nécessaire pour leurs premiers échanges.'},
 {id:'operations',pageId:'B003',url:'/pour-votre-equipe/responsable-operations/',label:'Je gère les opérations',role:'Responsable opérations',short:'Retrouver les stocks et les données utiles dans vos outils.',title:'Une disponibilité à retrouver, plusieurs fichiers à ouvrir.',intro:'Les fournisseurs envoient leurs stocks dans des formats différents. Votre équipe compare les références avant de répondre à un client ou de préparer un achat. Nous réunissons les données et rendons les cas incertains visibles.',scene:'operations',friction:'Chaque question de stock oblige à rechercher une référence dans plusieurs fichiers fournisseurs.',gain:'Une vue par référence rassemble les disponibilités connues et la date de chaque source. Les correspondances inconnues restent à confirmer.',tasks:['P025','P034','P027','P030','P031','P032'],service:'P014',caseId:'P053',caseText:'Des exécutions documentées rapprochent les fichiers fournisseurs des références Odoo et préparent les stocks consolidés.',keeps:'Votre équipe confirme les correspondances, les règles de disponibilité, les tarifs et les commandes. Une donnée fournisseur reste distincte de votre stock détenu.',first:'Commencez avec un fichier fournisseur, vos références produits et un exemple de résultat attendu. Nous vérifions les correspondances avant d’étendre à d’autres sources.',measure:'Comparez la recherche d’une disponibilité sur des références connues et ambiguës. Vérifiez les dates des sources et le temps passé à traiter les exceptions.',titleMeta:'Automatisation des stocks et opérations B2B | 100 Pilot',description:'Réunissez les stocks fournisseurs et préparez les données Odoo avec 100 Pilot. Retrouvez les disponibilités et les références à vérifier au même endroit.'}
];
export const personaByGroup={operations:'operations',catalogue:'operations',commercial:'commercial',admin:'direction',experience:'commercial',pilotage:'direction'};
export const personaPages=[
 {id:'B000',family:'Socle',url:'/pour-votre-equipe/',h1:'Quel travail voulez-vous confier au pilote automatique ?',title:'Automatisation selon votre rôle en entreprise | 100 Pilot',intro:'Vous dirigez l’entreprise, développez les ventes ou gérez les opérations. Partez de votre quotidien pour voir ce que nous pouvons préparer et ce qui reste à votre équipe.',description:'Dirigeant, responsable commercial ou opérations : découvrez les tâches que 100 Pilot peut automatiser à partir du quotidien de votre équipe.',refs:'',links:'/services/ ; /solutions/ ; /contact/',angle:''},
 ...personas.map(p=>({id:p.pageId,family:'Persona',role:p.role,url:p.url,h1:p.title,title:p.titleMeta,intro:p.intro,description:p.description,refs:'',links:'/pour-votre-equipe/ ; /services/ ; /contact/',angle:''}))
];
const scenes={
 operations:{label:'Une disponibilité fournisseur',before:['Fichier fournisseur','Références internes','Dernière mise à jour'],after:'Les stocks réunis par référence',rows:[['Référence reconnue','Disponibilités réunies'],['Source fournisseur','Date conservée'],['Référence inconnue','À confirmer']],human:'Votre équipe confirme les correspondances.'},
 catalogue:{label:'Une mise à jour de catalogue',before:['Caractéristiques produit','Fiches actuelles','Règles de rédaction'],after:'Les changements prêts à relire',rows:[['Titre et description','Propositions préparées'],['Caractéristiques','Sources visibles'],['Information absente','À compléter']],human:'Votre équipe valide avant publication.'},
 commercial:{label:'Une liste pour la prospection',before:['Votre offre','Critères de ciblage','Informations accessibles'],after:'Les contacts prêts à vérifier',rows:[['Entreprises retenues','Critères expliqués'],['Informations de contact','Sources disponibles'],['Besoin commercial','À qualifier']],human:'Votre commercial choisit les destinataires.'},
 admin:{label:'Une facture reçue par email',before:['Pièce jointe','Société concernée','Dossier de destination'],after:'Les pièces rangées pour l’équipe',rows:[['Société identifiée','Document classé'],['Pièce déjà reçue','Doublon signalé'],['Attribution incertaine','À vérifier']],human:'Votre équipe garde la validation comptable.'},
 experience:{label:'Une demande depuis votre site',before:['Besoin du visiteur','Réponses au questionnaire','Offres disponibles'],after:'Le contexte réuni pour l’échange',rows:[['Orientation','Explication affichée'],['Estimation','Hypothèses visibles'],['Demande de contact','Contexte choisi']],human:'Votre équipe confirme la prestation.'},
 pilotage:{label:'Un dossier à suivre',before:['Pièces du dossier','Étapes du traitement','Rôles de l’équipe'],after:'Les informations au bon endroit',rows:[['État du dossier','Étape visible'],['Pièce manquante','À demander'],['Décision attendue','Responsable identifié']],human:'Votre responsable valide la suite du dossier.'}
};
export function workflowPreview(group='operations',{compact=false,scene}={}){
 const s=scene||taskScenes[group]||scenes[group]||scenes.operations;
 return `<div class="work-preview ${compact?'compact':''}"><div class="preview-heading"><span>${s.label}</span><span class="example-chip">Exemple illustratif</span></div><div class="manual-files"><span class="preview-label">Le travail à préparer</span><div>${s.before.map((label,i)=>`<span class="source-file">${i===0?'↳':'▤'} ${label}</span>`).join('')}</div></div><div class="route-bridge">${trajectoryMark}<span>Le résultat à préparer</span></div><div class="prepared-result"><div class="result-heading"><span class="status-dot"></span><strong>${s.after}</strong></div>${s.rows.filter(([,value])=>value!==s.after).map(([a,b])=>`<div class="result-line"><span>${a}</span><span>${b}</span></div>`).join('')}</div><p class="human-note">${s.human}</p></div>`;
}
export function personaCards(){return `<div class="persona-grid">${personas.map((p,i)=>`<a class="persona-card" href="${p.url}"><span class="persona-number">0${i+1}</span><span class="persona-role">${p.label}</span><h3>${p.short}</h3><p>${p.friction}</p><span class="text-link">Voir mon quotidien <span aria-hidden="true">↗</span></span></a>`).join('')}</div>`;}
export function personaContext(group){const p=personas.find(p=>p.id===personaByGroup[group]);return p?`<span class="role-context"><a href="${p.url}">${p.role}</a> <span aria-hidden="true">/</span> Une tâche de votre quotidien</span>`:'';}
export function personaContent(p,{button,cards,pages}){
 if(p.id==='B000')return `<section class="section wrap"><div class="section-head"><h2>Trois façons de commencer.</h2><p>Votre métier donne le point de départ. Nous vous aidons à choisir une première tâche.</p></div>${personaCards()}</section><section class="section wrap"><div class="cta-band"><h2>Vous cherchez une autre tâche ?</h2>${button('/solutions/','Explorer toutes les solutions')}</div></section>`;
 const person=personas.find(r=>r.pageId===p.id);
 const casePage=pages.find(r=>r.id===person.caseId);
 return `<section class="section wrap"><div class="persona-situation"><div><span class="eyebrow">Dans votre quotidien</span><h2>${person.friction}</h2><p>${person.gain}</p><p class="quiet">Situation illustrative, à adapter à votre organisation.</p></div>${workflowPreview(person.scene)}</div></section><section class="section gray" id="taches"><div class="wrap"><div class="section-head"><h2>Les tâches que vous pouvez nous confier.</h2><p>Commencez par celle que votre équipe reconnaît. Nous précisons le résultat et les données avant de construire.</p></div>${cards(person.tasks.map(id=>pages.find(r=>r.id===id)).filter(Boolean))}</div></section><section class="section wrap"><div class="split-reading"><div><span class="eyebrow">Un premier projet</span><h2>Montrez-nous comment vous faites aujourd’hui.</h2><p>${person.first}</p><a class="text-link" href="/methode/">Voir le déroulement</a></div><div><h3>Ce que votre équipe continue à décider</h3><p>${person.keeps}</p><h3>Comment vérifier l’intérêt du résultat</h3><p>${person.measure}</p></div></div></section><section class="section dark"><div class="wrap proof-story"><div><span class="eyebrow">Travail documenté / Cas anonymisé</span><h2>${casePage.h1}</h2></div><div><p>${person.caseText}</p>${button(casePage.url,'Lire le travail documenté','light')}</div></div></section><section class="section wrap"><div class="cta-band"><div><h2>Quelle tâche revient dans votre semaine ?</h2><p>Décrivez-la avec vos mots. Vous n’avez pas besoin d’avoir choisi un outil.</p></div>${button('/contact/?sujet='+encodeURIComponent(person.role),'Parlons de votre équipe')}</div></section>`;
}
