import {workflows,groups} from './workflow-catalog.mjs';
import {publicCopy,routeChanges} from './public-copy.mjs';
import {pageEdits,caseEdits} from './human-copy.mjs';
const byWorkflow=Object.fromEntries(workflows.map(w=>[w.id,w]));
export const mergedPages=['P006','P080','P081','P082','P083'];
const overrides={
 P054:['/realisations/distribution-b2b-prospection/','Distribution B2B : préparer des listes de prospects'],
 P055:['/realisations/distribution-b2b-attributs-catalogue/','Distribution B2B : rendre les caractéristiques produits exploitables'],
 P056:['/realisations/distribution-b2b-nettoyage-catalogue/','Distribution B2B : préparer un catalogue plus cohérent'],
 P058:['/realisations/distribution-b2b-import-crm/','Distribution B2B : préparer les contacts à importer'],
 P059:['/realisations/recrutement-parcours-commercial/','Recrutement B2B : aider le visiteur à préparer sa demande'],
 P060:['/realisations/recrutement-quiz-orientation/','Recrutement B2B : orienter un besoin en quelques questions'],
 P061:['/realisations/recrutement-calculateur/','Recrutement B2B : expliquer les coûts avant le premier échange'],
 P062:['/realisations/services-b2b-contenus/','Services B2B : expliquer les offres sur des pages dédiées'],
 P063:['/realisations/formation-manuel-technique/','Formation technique : assembler un manuel depuis les sources'],
 P064:['/realisations/infrastructure-prospection-email/','Prospection : préparer et tester l’infrastructure email'],
 P065:['/etudes/diagnostic-portail-suivi/','Diagnostic : suivre le dossier, les pièces et le devis','Étude'],
 P066:['/realisations/ecommerce-parcours-langues/','E-commerce : orienter chaque public vers le bon parcours'],
 P067:['/realisations/ecommerce-publication-supervisee/','Projet interne : préparer et vérifier la publication de produits'],
 P068:['/etudes/migration-site-multilingue/','Site multilingue : préparer la migration et ses contrôles','Étude'],
 P069:['/etudes/marketing-assistants-supervises/','Marketing : préparer les actions avec une validation humaine','Étude'],
 P072:['/etudes/sport-textile-prospection/','Sport & textile : préparer deux prospections distinctes'],
 P074:['/etudes/retail-programme-fidelite/','Retail : retrouver les membres et suivre leurs avantages'],
 P075:['/etudes/restauration-commandes-fidelite/','Restauration : préparer commandes directes et fidélité'],
 P076:['/etudes/production-tracabilite-lots/','Production : retrouver l’historique des lots et les pistes acheteurs'],
 P077:['/etudes/missions-disponibilites/','Missions : réunir disponibilités et dossiers administratifs'],
 P078:['/realisations/audit-site-b2b/','Site B2B : repérer les obstacles avant l’acquisition','Réalisation'],
 P079:['/etudes/ecommerce-catalogue-multilingue/','E-commerce : préparer les contenus et parcours multilingues']
};
const extras=[
 ['P104','Solution','/solutions/marges-circuits-vente/','Comparer les marges par circuit de vente','S14'],
 ['P105','Solution','/solutions/preparation-import-crm/','Préparer les créations et mises à jour de contacts','S11'],
 ['P106','Solution','/solutions/commandes-directes/','Un parcours de commande directe pour vos clients','S20'],
 ['P107','Solution','/solutions/assistant-commande-bilingue/','Répondre aux questions de commande dans deux langues','S20'],
 ['P108','Solution','/solutions/tracabilite-lots/','Retrouver l’historique et les pièces d’un lot','S21'],
 ['P109','Solution','/solutions/rapprochement-lots-acheteurs/','Comparer les lots aux besoins des acheteurs','S21'],
 ['P110','Solution','/solutions/suivi-missions-disponibilites/','Réunir disponibilités, missions et pièces','S24'],
 ['P111','Étude','/etudes/hotellerie-suivi-operations/','Prototype interne : relier réservations et préparation des chambres','S30']
];
export const aliases={...routeChanges,...Object.fromEntries(Object.entries(overrides).map(([id,row])=>[id,row[0]]))};
export function makePages(inventory){
 const selected=inventory.pages.filter(p=>!mergedPages.includes(p.id));
 const urlMap={...routeChanges};for(const p of selected)if(overrides[p.id])urlMap[p.url]=overrides[p.id][0];
 const pages=publicCopy(selected).map(p=>{const row=overrides[p.id];if(row)p={...p,url:row[0],h1:row[1],family:row[2]||p.family};p.links=p.links.split(' ; ').map(u=>urlMap[u]||u).join(' ; ');return p;});
 for(const [id,family,url,h1,refs] of extras)pages.push({id,family,url,h1,title:h1+' | 100 Pilot',priority:'P2',refs,links:'/services/ ; /solutions/ ; /contact/',ds:'',angle:''});
 for(const p of pages){const profile=profiles[p.id];if(profile&&p.family==='Solution')p.h1=profile.title;if(cases[p.id]?.title)p.h1=cases[p.id].title;p.title=p.h1+' | 100 Pilot';}
 return pages;
}
export const profiles={};
for(const w of workflows)for(const id of w.pageIds)if(!profiles[id])profiles[id]=w;
function profile(id,base,fields){profiles[id]={...(profiles[id]||byWorkflow[base]),...fields};}
profile('P035','W02',{title:'Complétez vos fiches entreprises pour mieux préparer les contacts',intro:'Nous préparons les informations utiles à vos fiches entreprises : activité, identifiants et coordonnées disponibles. Votre commercial passe moins de temps à rechercher le contexte avant un échange.',today:'Les fiches contiennent un nom et quelques coordonnées. Le commercial recherche à nouveau l’activité ou les identifiants à chaque contact.',action:'Nous rapprochons les entreprises des sources accessibles et présentons les informations proposées avec leur origine.',result:'Un fichier d’enrichissement : informations proposées, sources et champs qui demandent une vérification.',benefit:['Moins de recherches répétées avant un contact.','Un contexte commercial plus facile à retrouver.','Les informations proposées sont séparées des données validées.'],example:['Préparer un appel à une entreprise peu renseignée','La fiche proposée réunit son activité et les identifiants disponibles. Le commercial vérifie les informations utiles avant l’appel. Les champs inconnus restent à compléter.']});
profile('P052','W01',{title:'Relier les tâches de stock, catalogue et contacts autour d’Odoo',benefit:['Une même logique de préparation pour plusieurs tâches répétitives.','Des données plus faciles à retrouver dans les formats de travail.','Des fichiers de vérification avant les modifications sensibles.'],result:'Des traitements et fichiers de préparation pour les stocks, le catalogue, la prospection et le rapprochement de contacts.',example:['Un fournisseur met à jour son fichier','Le stock est préparé par référence. Les informations produit et contacts suivent leurs propres traitements : une consolidation de stock ne déclenche pas automatiquement une modification du catalogue ou du CRM.']});
profile('P059','W23',{title:'Un visiteur mieux orienté, une demande mieux préparée',result:'Un quiz d’orientation, un calculateur de coût et un parcours de contact contextualisé.',benefit:['Le visiteur comprend mieux quelle offre explorer.','Il peut préparer une estimation avant le premier échange.','Le commercial retrouve le contexte de la demande.'],example:['Le visiteur hésite sur le type de recrutement','Le quiz explique un point de départ, le calculateur rend les hypothèses de coût visibles, puis le contact reprend les informations que le visiteur transmet.']});
profile('P070','W14',{title:'Repérer les tâches répétitives d’un équipementier B2B',intro:'Une étude pour relier achats, disponibilité, prix, prospection et documents. L’objectif : préparer les informations dont l’équipe a besoin, sans refaire les mêmes comparaisons à chaque opération.',result:'Huit scénarios distincts, chacun avec ses données de départ et le livrable envisagé.',benefit:['Une vue des tâches qui pourraient être préparées automatiquement.','Un premier choix possible selon les données déjà disponibles.','Des achats, prix et documents dont les décisions restent à l’équipe.'],example:['Choisir un premier scénario parmi huit idées','L’équipe peut commencer par le classement des pièces ou la préparation des achats selon ses données. Le choix porte sur un résultat utile à tester avant d’étendre les autres scénarios.']});
profile('P072','W17',{title:'Séparez la prospection des clubs et celle des entreprises',intro:'L’étude propose deux listes adaptées à deux offres : équipements pour clubs sportifs et textile pour entreprises. Chaque segment reçoit ses critères et sa préparation commerciale.',result:'Deux fichiers de cibles envisagés, avec leurs critères et les informations à vérifier.',benefit:['Des cibles liées à une offre précise.','Des messages commerciaux qui peuvent être adaptés au segment.','Moins de mélange entre besoins sportifs et besoins d’entreprise.'],example:['Une même entreprise vend deux gammes','Les clubs sont regroupés selon discipline et zone. Les entreprises sont sélectionnées selon l’activité et l’usage textile possible. Le commercial confirme les besoins avant de proposer sa gamme.']});
profile('P076','W33',{title:'Retrouver les pièces d’un lot et préparer sa présentation aux acheteurs',result:'Un prototype de fiches de lots, de suivi des pièces et de pistes de rapprochement avec des besoins acheteurs.',example:['Présenter un lot à un acheteur potentiel','La démonstration réunit les caractéristiques et pièces du lot. Des critères de besoin acheteur servent à préparer des correspondances possibles, toujours à vérifier commercialement.']});
const services=[
 ['P013','W39','Identifiez les tâches qui valent la peine d’être automatisées','Vous avez plusieurs tâches chronophages ? Nous les comparons avec vous pour choisir un premier projet utile, réaliste et facile à évaluer.','Des priorités expliquées, les données nécessaires et un premier projet à chiffrer.',['Évitez de commencer par une idée coûteuse et difficile à exploiter.','Concentrez votre premier investissement sur une tâche identifiable.','Sachez ce qui doit être prêt pour lancer le projet.']],
 ['P014','W01','Faites circuler vos données autour d’Odoo, sans les recopier','Nous relions vos fichiers et tâches à Odoo pour préparer stocks, catalogue ou contacts. Votre équipe reçoit les informations dans le format dont elle a besoin.','Un ou plusieurs flux choisis : données de stock, produits ou contacts préparés pour votre usage.',['Moins de recopie entre fichiers et outil de gestion.','Des informations organisées pour les achats, ventes ou le catalogue.','Une vérification des changements avant les mises à jour sensibles.']],
 ['P015','W02','Plus de temps pour vendre, moins de temps pour chercher des contacts','Nous préparons le ciblage, les listes et les informations nécessaires à votre prospection. Votre commercial se concentre sur les échanges et les opportunités.','Une liste ciblée et segmentée, avec les informations utiles à la prise de contact.',['Moins de recherche manuelle pour démarrer une campagne.','Des entreprises sélectionnées pour votre offre.','Des contacts et critères faciles à revoir avec votre équipe.']],
 ['P016','W19','Des fiches produits qui répondent aux questions des acheteurs','Nous préparons des contenus produits clairs à partir de vos données. Votre équipe gagne du temps sur la rédaction et se concentre sur la vérification des informations.','Des textes et attributs proposés, un format éditorial et une vue de validation.',['Moins de rédaction répétitive.','Des différences entre produits plus faciles à comprendre.','Une base cohérente pour ajouter de nouvelles références.']],
 ['P017','W20','Moins de classement et de suivi administratif à la main','Nous préparons le traitement des pièces, échéances et relances pour que votre équipe retrouve les documents et sache quelles actions restent à faire.','Des documents classés, une liste d’échéances ou des relances préparées selon la tâche choisie.',['Moins de manipulation de pièces jointes.','Des documents et actions plus faciles à retrouver.','Les décisions comptables et messages sensibles restent contrôlés.']],
 ['P018','W45','Confiez la préparation répétitive à un assistant, gardez la décision','Nous mettons en place un pilote où un assistant prépare une tâche à partir de vos informations. Votre équipe approuve les actions importantes.','Un assistant limité à une tâche, ses propositions et un circuit de validation.',['Moins d’aller-retours entre outils pour préparer une action.','Des propositions réunies pour décider.','Un périmètre d’autonomie explicite.']],
 ['P019','W28','Un même endroit pour suivre vos dossiers et savoir quoi faire','Nous concevons un portail adapté à votre processus : qui intervient, où en est le dossier et quelle information chaque personne peut consulter.','Des écrans de suivi, des statuts et des droits d’accès adaptés à vos rôles.',['Un statut de dossier plus simple à retrouver.','Moins de demandes internes de mise à jour.','Des informations distinctes pour l’équipe et le client.']],
 ['P020','W26','Vos experts relisent le fond, nous préparons le document','Nous organisons vos sources techniques et préparons un document structuré à relire, pour réduire le travail de copie, de rangement et de mise en page.','Des chapitres préparés, un document éditable et une relecture organisée.',['Moins d’assemblage manuel depuis les sources.','Une structure commune pour les supports.','Une relecture concentrée sur les informations importantes.']],
 ['P021','W39','Un site qui explique votre offre et se laisse trouver plus facilement','Nous vérifions ce que les visiteurs comprennent, comment ils vous contactent et quels points techniques ou éditoriaux gênent l’accès aux bonnes pages.','Un audit des pages et parcours, avec des corrections priorisées.',['Comprenez les obstacles rencontrés par votre prospect.','Choisissez des corrections liées à des problèmes observés.','Rendez vos informations plus faciles à lire et à vérifier.']],
 ['P022','W23','Aidez vos visiteurs à préparer une demande commerciale utile','Nous créons des quiz, calculateurs et formulaires contextualisés pour que vos prospects comprennent mieux leur besoin avant de vous contacter.','Un outil de qualification ou d’estimation relié à votre contact.',['Une orientation accessible aux visiteurs débutants.','Des hypothèses expliquées avant l’échange.','Des demandes qui transmettent davantage de contexte utile.']],
 ['P023','W28','Testez votre idée métier avant de lancer un projet complet','Nous préparons un prototype pour que votre équipe teste les écrans et le parcours avec des exemples. Vous choisissez ce qui mérite d’être développé.','Un prototype de démonstration, les retours d’usage et le périmètre de la suite.',['Validez l’usage avant d’élargir l’investissement.','Repérez les étapes et données manquantes.','Partagez une démonstration concrète avec votre équipe.']],
 ['P024','W47','Vos automatisations suivies, vos problèmes visibles','Nous organisons le suivi des résultats et la reprise des traitements pour que votre équipe sache quand intervenir et comment repartir.','Des contrôles de résultat, des alertes utiles et une procédure de reprise.',['Repérez les traitements incomplets avant qu’ils s’accumulent.','Sachez qui traite les exceptions.','Préparez les changements de fichiers et de règles.']]
];
for(const [id,base,title,intro,result,benefit] of services)profile(id,base,{title,intro,result,benefit});
const integrations=[
 ['P089','W01','Odoo','Nous pouvons préparer des données de stock, de produit ou de contact pour Odoo, puis définir les mises à jour utiles avec votre équipe.','Un fichier vérifié ou une connexion adaptée aux objets Odoo concernés.',['Moins de recopie depuis les fichiers métier.','Des données préparées dans les champs utilisés par votre équipe.','Un premier test avant de modifier la base.']],
 ['P090','W20','Google Drive','Nous pouvons utiliser vos dossiers Drive pour ranger et retrouver les pièces selon vos règles de société, période ou type de document.','Des dossiers organisés, des documents classés et les pièces incertaines à vérifier.',['Moins de déplacements manuels entre dossiers.','Des documents rangés selon une règle commune.','Une séparation claire des pièces de plusieurs sociétés.']],
 ['P091','W20','vos boîtes email','Nous pouvons utiliser les emails et pièces jointes autorisés comme point de départ d’un classement ou d’un suivi administratif.','Un traitement des messages concernés et une liste des pièces ou actions préparées.',['Moins d’ouverture manuelle de pièces répétitives.','Des documents envoyés vers le circuit utile.','Les exceptions sont visibles pour l’équipe.']],
 ['P092','W01','vos fichiers fournisseurs','Nous pouvons lire vos sources Excel, CSV ou les connexions disponibles pour les transformer en informations utilisables par votre équipe.','Des données regroupées, les correspondances et les sources à vérifier.',['Moins de transformations de fichiers à chaque réception.','Une vue cohérente malgré des formats différents.','La source et sa date restent identifiables.']],
 ['P093','W23','WordPress','Nous pouvons relier vos pages WordPress à des quiz, calculateurs et formulaires qui aident le prospect à préparer sa demande.','Des outils intégrés à vos pages et un parcours de contact contextualisé.',['Une offre plus facile à explorer.','Des informations utiles transmises au commercial.','Un parcours testé sur mobile et desktop.']]
];
for(const [id,base,tool,intro,result,benefit] of integrations)profile(id,base,{title:`Gardez ${tool} dans votre manière de travailler`,intro,result,benefit});
const sectors=[
 ['P084','W01','distribution B2B',['P025','P030','P034','P028'],'Une disponibilité à confirmer, une grille de prix à recalculer, des contacts à rapprocher : nous préparons les données qui font avancer vos achats et vos ventes.'],
 ['P085','W14','sport et textile B2B',['P026','P031','P037','P038'],'Tailles, achats, prix revendeurs et prospection : nous aidons votre équipe à préparer ses opérations à partir de données réunies.'],
 ['P086','W23','services B2B',['P036','P043','P044','P045'],'Nous aidons vos commerciaux à retrouver les bonnes cibles et vos visiteurs à comprendre l’offre, estimer un besoin et transmettre une demande utile.'],
 ['P087','W30','restauration et retail',['P106','P107','P046'],'Commandes directes, questions clients et fidélité : nous pouvons cadrer les parcours utiles et vérifier les connexions à votre caisse avant développement.'],
 ['P088','W26','formation technique',['P048'],'Vos informations sont déjà dans les sources. Nous les organisons en supports structurés pour que vos experts se concentrent sur la relecture du fond.']
];
for(const [id,base,sector,children,intro] of sectors)profile(id,base,{title:`Les tâches que nous pouvons préparer en ${sector}`,intro,children});
export const serviceChildren={P013:['P025','P040','P043'],P014:['P025','P027','P029','P030','P031','P034','P105'],P015:['P036','P035','P037','P038','P039'],P016:['P032','P049','P050'],P017:['P040','P041','P028','P042'],P018:['P051'],P019:['P047','P108','P110'],P020:['P048'],P021:['P078','P066'],P022:['P043','P044','P045'],P023:['P065','P075','P076','P077','P111'],P024:['P051','P050']};
export const serviceIds=services.map(row=>row[0]);
profile('P013','W39',{today:'Les mêmes tâches reviennent chaque semaine, mais vous ne savez pas lesquelles automatiser en premier ni quelles données seraient nécessaires.',action:'Nous observons quelques tâches avec votre équipe et comparons leur fréquence, le temps passé, les données et la difficulté. Vous recevez des priorités et un premier projet défini.',steps:[['Décrire votre quotidien','Votre équipe montre les fichiers, outils et gestes qui reviennent.'],['Comparer les tâches','Nous confrontons le temps passé aux données et dépendances disponibles.'],['Choisir le premier projet','Le résultat utile, les accès et les critères de test sont précisés.']],needs:['Quelques tâches qui reviennent souvent.','Des exemples de fichiers ou documents anonymisés.','Une personne qui connaît les règles et valide le résultat.'],example:['Choisir entre classement des factures et préparation des achats','Les deux tâches prennent du temps. Le classement peut être plus facile à tester si les pièces et dossiers existent déjà. Les achats demandent peut-être de compléter les reliquats. Vous choisissez avec une vue des conditions et de l’utilité attendue.']});
for(const id of serviceIds)profiles[id].children=serviceChildren[id];
const guides=[
 ['P094','W39','Choisissez une première tâche utile à automatiser','Vous n’avez pas besoin de commencer par tout votre fonctionnement. Ce guide aide à comparer quelques tâches pour choisir un premier projet que votre équipe pourra vraiment utiliser.','Une liste courte de tâches, classée selon le temps passé, les données disponibles et le résultat attendu.','Les idées sont nombreuses, mais leur fréquence et les conditions de mise en place ne sont pas décrites.','Pour chaque tâche, notez quand elle revient, combien de temps elle prend, ce qui entre dans le traitement et ce qui doit en sortir.',['Choisissez selon le besoin réel de l’équipe.','Repérez les données à préparer avant de demander un devis.','Définissez une sortie vérifiable pour le premier test.'],['Comparer deux tâches quotidiennes','Le classement de pièces dispose déjà de boîtes et de dossiers définis. La préparation des achats dépend d’un export encore indisponible. Vous pouvez démarrer par le premier et préparer les données du second.'],[['Lister les tâches','Retenez celles que l’équipe refait souvent.'],['Décrire la sortie','Dites ce que l’automatisation devrait fournir.'],['Comparer les conditions','Vérifiez les données et validations disponibles.']]],
 ['P095','W47','Estimez le temps utile gagné avant de parler de ROI','Ce guide vous aide à comparer le travail actuel et un test d’automatisation, puis à intégrer les coûts de mise en place, d’usage et de suivi.','Une comparaison du temps avant/après et des coûts connus, avec les hypothèses clairement indiquées.','Le gain annoncé peut oublier le temps de relecture, les exceptions et les coûts récurrents.','Mesurez le travail actuel, puis le temps restant après le test. Valorisez ce temps avec une hypothèse explicite et comparez-le aux coûts du projet.',['Comparez la charge réelle de l’équipe.','Incluez la vérification et les exceptions dans le calcul.','Séparez une estimation d’un résultat observé.'],['Exemple de calcul, sans résultat client revendiqué','Une tâche de 30 minutes répétée 20 fois représente 10 heures. Si le test laisse 5 minutes de vérification à chaque passage, il reste 1 heure 40. L’écart illustratif est de 8 heures 20, avant maintenance et incidents. Pour comparer un coût en euros, il faut ensuite choisir une valeur horaire et ajouter les coûts réels.'],[['Mesurer avant','Chronométrez plusieurs passages représentatifs.'],['Mesurer après','Incluez revue, corrections et reprises.'],['Comparer les coûts','Ajoutez installation, usage et suivi.']]],
 ['P096','W45','Choisissez une règle simple ou un assistant selon la tâche','Une comparaison de prix n’a pas le même besoin qu’un résumé de document. Ce guide aide à choisir une approche à partir de la tâche, sans partir de la technologie.','Une distinction entre règles déterminées, préparation assistée et décisions qui restent à une personne.','L’IA est parfois choisie avant de savoir si le résultat suit déjà une règle précise.','Identifiez ce qui se calcule, ce qui demande de lire un contenu variable et ce qui engage une décision.',['Évitez d’ajouter de la complexité à un calcul simple.','Utilisez l’assistance pour préparer des informations variables.','Gardez les décisions importantes visibles.'],['Comparer une grille de prix et un résumé de facture','Une marge et un arrondi définis suivent une règle. Lire un document de présentation variable peut demander une extraction assistée. Confirmer un paiement ou une exception relève du circuit de validation.'],[['Décrire le résultat','Précisez ce que l’équipe attend.'],['Chercher une règle','Vérifiez si la réponse est déterminée par les données.'],['Prévoir la validation','Décidez qui traite les informations incertaines.']]],
 ['P097','W45','Placez la validation là où elle change une décision','Une validation utile montre à la personne ce qu’elle doit décider. Ce guide aide à éviter les relectures générales qui bloquent tout sans expliquer les risques.','Une liste de décisions et les informations nécessaires à chaque personne pour les confirmer.','Votre équipe reçoit un fichier entier à approuver, sans savoir quels champs ont changé ni quels cas sont incertains.','Présentez les différences, la raison du changement et les exceptions, puis attribuez chaque décision à une personne.',['Concentrez la relecture sur les cas importants.','Donnez les informations nécessaires pour décider.','Évitez une validation automatique de façade.'],['Valider une mise à jour de contacts','La personne voit les champs proposés à côté des valeurs actuelles et la raison du rapprochement. Elle confirme le changement ou conserve la valeur avant l’import.'],[['Identifier les décisions','Séparez routine et exceptions.'],['Montrer les différences','Présentez ancien, proposé et raison.'],['Attribuer la revue','Précisez qui valide et comment reprendre.']]],
 ['P098','W07','Préparez les données avant une intégration Odoo','Ce guide aide à préparer un premier échange sur Odoo : quels champs, quels accès et quel exemple de résultat faut-il rassembler ?','Un petit jeu d’exemples, la source de chaque donnée et le format attendu dans Odoo.','Un fichier existe, mais on ne sait pas quel champ Odoo doit recevoir chaque colonne ni comment reconnaître les produits ou contacts.','Commencez par un export, quelques exemples complets et quelques cas incomplets. Définissez les correspondances avant un import.',['Réduisez les inconnues avant le premier test.','Montrez les exceptions au lieu de les découvrir lors de l’import.','Définissez le résultat attendu avec votre équipe.'],['Préparer dix exemples de contacts','Vous sélectionnez nouveaux contacts, contacts existants et doublons possibles. Vous indiquez les champs à garder et les changements souhaités. Le premier test vérifie la manière de traiter chaque cas.'],[['Choisir un objet','Stock, produit ou contact.'],['Préparer les exemples','Incluez cas habituels et exceptions.'],['Vérifier avant écriture','Comparez le résultat proposé à celui attendu.']]],
 ['P099','W20','Séparez les pièces de chaque société dès leur réception','Ce guide aide à organiser les boîtes, dossiers et identifiants avant d’automatiser le classement de factures de plusieurs sociétés.','Un plan de classement et une règle pour les documents dont la société est incertaine.','Les pièces de plusieurs sociétés passent par la même équipe et se retrouvent mélangées dans les dossiers.','Associez une boîte ou une origine connue à la société, vérifiez l’identité sur les pièces et prévoyez une revue des documents ambigus.',['Des pièces plus faciles à retrouver par société.','Une transmission comptable plus organisée.','Les cas incertains sont séparés du classement courant.'],['Une pièce arrive sans société clairement lisible','Elle reste dans le dossier de vérification. La personne responsable l’attribue avant transmission, plutôt que de supposer une société depuis le fournisseur.'],[['Organiser les origines','Distinguez les boîtes et sociétés.'],['Définir les dossiers','Choisissez période, type et nommage.'],['Prévoir les exceptions','Attribuez la revue des pièces douteuses.']]],
 ['P100','W04','Relisez les informations qui aident l’acheteur à choisir','Ce guide propose une relecture de fiches produits centrée sur les caractéristiques, les différences utiles et les informations que vous pouvez réellement vérifier.','Une liste de points à relire avant publication, par famille de produits.','Un texte peut sembler convaincant tout en ajoutant une compatibilité, une dimension ou un usage absent de vos sources.','Reliez les informations aux attributs disponibles, relisez les champs techniques et comparez les variantes avant de publier.',['Vérifiez les caractéristiques qui influencent l’achat.','Repérez les ajouts absents des sources.','Conservez les différences entre variantes.'],['Relire deux tailles d’un même modèle','La matière peut être commune, mais dimensions et références diffèrent. La relecture contrôle chaque variante au lieu d’approuver seulement le texte général.'],[['Relier aux sources','Retrouvez l’origine des caractéristiques.'],['Comparer les variantes','Contrôlez dimensions et codes.'],['Relire la page','Vérifiez les informations réellement visibles.']]],
 ['P101','W06','Rapprochez les contacts avec des identifiants fiables','Ce guide aide à préparer une comparaison de bases clients sans confondre ressemblance de nom et correspondance confirmée.','Une grille de correspondances, avec les identifiants utilisés et les cas à relire.','Un nom commercial ressemble à une autre société. Une fusion sur le seul nom peut faire perdre des informations.','Comparez d’abord les identifiants communs disponibles, puis présentez les pistes moins certaines pour vérification.',['Des rapprochements dont la raison est lisible.','Les ambiguïtés restent séparées des correspondances certaines.','Une préparation plus claire des créations et mises à jour.'],['Deux entreprises ont un nom presque identique','Des identifiants ou adresses différents indiquent qu’elles ne doivent pas être fusionnées. Si les identifiants manquent, le rapprochement reste une proposition à vérifier.'],[['Lister les clés','Identifiants, emails et adresses disponibles.'],['Comparer par niveaux','Séparez certain, possible et absent.'],['Valider les actions','Confirmez fusion ou mise à jour avant l’import.']]],
 ['P102','W28','Vérifiez ce qui manque entre une démonstration et l’usage réel','Ce guide vous aide à passer d’écrans qui montrent une idée à un outil qui traite réellement vos dossiers et exceptions.','Une liste des parcours réels à vérifier avant mise en service.','Une démonstration fonctionne sur des exemples, mais les accès, notifications, erreurs et reprises ne sont pas encore testés.','Vérifiez chaque parcours jusqu’au résultat attendu avec des utilisateurs et des données autorisées.',['Repérez les connexions qui restent à développer.','Testez les erreurs avant l’usage quotidien.','Distinguez écran de démonstration et résultat opérationnel.'],['Un portail prépare un email','Voir le message dans un écran ne prouve pas sa réception. Le test doit confirmer le destinataire, le contenu reçu et le comportement si l’envoi échoue.'],[['Lister les parcours','Incluez exceptions et reprise.'],['Tester les connexions','Vérifiez les outils et accès réels.'],['Valider la sortie','Confirmez la réception ou donnée finale.']]],
 ['P103','W39','Écrivez un cas qui aide vraiment votre futur client','Un cas utile explique un problème reconnaissable, le travail effectué et son résultat documenté. Ce guide aide à produire une page qui apprend quelque chose au lecteur.','Un plan de cas concret, avec faits, exemple, livrable et limites.','Une page annonce de l’IA ou une automatisation sans expliquer ce que l’équipe reçoit ni comment le travail quotidien change.','Décrivez la tâche avant, le livrable préparé et ce que le dossier prouve. Séparez un exemple illustratif d’un résultat mesuré.',['Le lecteur reconnaît son propre besoin.','Le livrable et sa valeur deviennent compréhensibles.','Les réalisations et propositions restent distinctes.'],['Présenter un fichier de stock consolidé','Expliquez les fichiers séparés au départ, la liste commune préparée et les références à revoir. Une économie de temps chiffrée ne s’ajoute que si elle a été mesurée.'],[['Partir de la tâche','Décrivez le quotidien de l’équipe.'],['Montrer la sortie','Expliquez ce qui est utilisable.'],['Appuyer les faits','Indiquez ce qui est documenté ou proposé.']]]
];
for(const [id,base,title,intro,result,today,action,benefit,example,steps] of guides)profile(id,base,{title,intro,result,today,action,benefit,example,steps,resource:true,needs:['Une tâche ou un projet réel à décrire.','Quelques exemples anonymisés.','La personne qui utilise ou valide le résultat.'],approval:'Appliquez la méthode sur un petit exemple avant de l’étendre. Les hypothèses et exceptions doivent rester visibles.',questions:[['Dois-je connaître les outils techniques pour commencer ?','Non. Décrivez votre tâche, les fichiers utilisés et ce que vous aimeriez obtenir. Cela suffit pour préparer les premières questions.'],['Quel exemple préparer pour un premier échange ?',`Choisissez une situation représentative de ce guide. ${example[1]} Un exemple anonymisé permet de comprendre la règle sans transmettre de données inutiles.`]]});
export const cases={};
function evidence(id,status,proof,action,result,limit='Le dossier documente le travail et son livrable. Il ne fournit pas de mesure de temps gagné ou de résultat commercial attribué.'){cases[id]={status,proof,action,result,limit,label:status.includes('proposé')||status.includes('Prototype')?'Le scénario étudié':'Ce qui est documenté'};}
evidence('P052','Travaux documentés','Le dossier réunit des traitements autour d’Odoo et des fichiers de stocks, de catalogue, de prospection et de contacts. Chaque tâche possède son propre état. Les extensions envisagées ne sont pas présentées comme déjà livrées.','Des flux et sorties de préparation sont décrits pour plusieurs tâches de distribution B2B. Les stocks et rapprochements sont documentés par des exécutions ou exports.','Des fichiers de préparation et de vérification, avec un état distinct par traitement.');
evidence('P053','Exécutions documentées','Des exécutions du moteur de rapprochement et consolidation de stocks sont documentées au 24 septembre 2026. Le traitement relie les références fournisseurs aux produits Odoo.','Le moteur rapproche les références connues et prépare les disponibilités. Les lignes inconnues demandent une vérification.','Une préparation de stock consolidé et des traces de traitement.');
evidence('P054','Fichier de prospection documenté','Un livrable de sourcing et de qualification d’entreprises est présent dans le dossier. Il décrit une préparation commerciale, sans vente attribuée.','Les entreprises recherchées ont été réunies dans un fichier destiné à la qualification commerciale.','Un tableau de prospects et informations de qualification.');
evidence('P055','Travaux de catalogue documentés','La structuration d’attributs est citée dans le périmètre de travaux du catalogue. Le cas explique cette préparation de données, sans présenter une nouvelle intégration comme acquise.','Les caractéristiques produits sont organisées pour préparer leur utilisation dans le catalogue.','Des données et règles de structuration du catalogue.');
evidence('P056','Fichier de catalogue documenté','Un fichier de travail sur la cohérence du catalogue est présent. Ce cas présente la préparation des corrections.','Les champs et incohérences ont été organisés dans un livrable à vérifier avant import.','Un fichier de catalogue et les corrections à relire.');
evidence('P057','Exports de rapprochement documentés','Le dossier décrit le rapprochement entre deux bases avec plusieurs identifiants et des exports consultatifs. Les résultats restent distincts d’une écriture dans Odoo.','Les contacts ont été comparés et les correspondances préparées pour une validation.','Des exports de correspondances et d’exceptions à relire.');
evidence('P058','Exports d’import documentés','Des exports de préparation des créations et mises à jour de contacts sont présents dans le dossier. Le cas porte sur la préparation du fichier.','Les informations destinées à l’import sont organisées pour distinguer les actions à faire.','Des fichiers de préparation d’import CRM.');
evidence('P059','Parcours déployés et testés','La livraison du 12 septembre 2026 documente un calculateur, un quiz et un contact contextuel sur un site de recrutement B2B. Les parcours et le rendu mobile ont été vérifiés. Aucun gain de leads n’est attribué.','Trois outils ont été reliés aux pages et au formulaire employeur existant. Le prospect peut préparer son besoin avant l’échange.','Un quiz, un calculateur et un contact qui reprend le contexte transmis.');
evidence('P060','Quiz déployé et testé','Le quiz documenté pose sept questions sur urgence, durée, volume, budget et organisation du besoin. Il propose une orientation et une alternative expliquées.','Les réponses sont comparées à une grille de choix des modèles de staffing, puis un contact contextualisé est proposé.','Une recommandation indicative et un contexte transmis au contact.');
evidence('P061','Calculateur déployé et testé','Le calculateur documenté prend en compte le poste, le salaire, le nombre de recrutements, les jours de vacance, l’effort interne et les frais d’outils. Les hypothèses restent visibles.','Les postes de coût sont présentés et une fourchette de préparation est calculée selon les hypothèses choisies.','Un détail des coûts et une estimation expliquée, distincte d’un devis.');
evidence('P062','Contenus documentés','Les rapports du projet décrivent des pages de services et du contenu éditorial. Les chiffres de trafic ne sont pas utilisés ici pour attribuer un résultat commercial.','Les offres et contenus sont organisés sur des pages dédiées et reliés aux parcours utiles.','Des pages de services et des contenus éditoriaux documentés.');
evidence('P063','Document final documenté','Le dossier de formation contient un pipeline de préparation de chapitres et un document final Word pour un manuel de formation. Le contenu doit être relu par des experts.','Les sources ont été organisées, les chapitres préparés et le document assemblé dans un format éditable.','Un manuel Word structuré et des éléments de contrôle des chapitres.');
evidence('P064','Installation et tests documentés','Le dossier décrit une infrastructure email et des tests. Certains réglages et limites de montée en charge nécessitent un suivi actualisé.','Les boîtes, l’authentification et les parcours de test ont fait l’objet d’une préparation.','Des réglages et résultats de tests documentés.');
evidence('P065','Prototype métier','Le projet de portail de diagnostic est partiellement développé : rôles, états de dossier et préparation de devis. L’exploitation complète, la réception des emails et le paiement ne sont pas présentés comme validés.','Le parcours relie statut, documents, rôles et préparation du devis dans un développement à compléter.','Un prototype partiel de suivi de dossiers et de devis.','Une mise en service exige encore de vérifier les parcours complets, les accès et les notifications.');
evidence('P066','Intervention documentée','Des interventions sur les adresses multilingues et la distinction des parcours particuliers et professionnels sont documentées. Le cas porte sur ces changements de parcours.','Les liens, redirections et appels à l’action sont adaptés aux langues et aux publics concernés.','Des parcours et adresses préparés et contrôlés dans le périmètre de l’intervention.');
evidence('P067','Projet interne documenté','Un premier produit publié et les étapes de préparation sont documentés dans un projet interne e-commerce. Ce test ne prouve pas la publication de toutes les gammes, langues ou boutiques.','Le processus prépare les données, contenus et validations, puis vérifie une première publication visible.','Un premier parcours de publication documenté et une méthode de vérification.');
evidence('P068','Préparation de migration','Le dossier décrit une version de préparation multilingue et des contrôles. La bascule finale du site public n’est pas documentée dans ces sources.','Les pages, langues et parcours ont été organisés et testés sur une version de préparation.','Une préparation de migration et les contrôles associés.','Le cas décrit une préparation. La bascule et ses résultats publics restent des étapes à confirmer.');
evidence('P069','Pilote supervisé','Le dossier décrit une version alpha supervisée d’orchestration marketing. Certaines connexions et tests restent à qualifier.','Des actions sont préparées dans un périmètre limité, avec validation avant les actions externes.','Une démonstration supervisée et des limites de fonctionnement identifiées.','Le pilote sert à tester un périmètre. Il ne constitue pas une plateforme autonome complète.');
for(const id of ['P070','P071','P072','P073'])evidence(id,'Scénario proposé','L’étude d’un équipementier sport et textile décrit huit opportunités : commandes, disponibilités, prix revendeurs, deux prospections, contenus, classement des pièces et relances. Les dernières corrections prévoient notamment une boîte par société pour les factures.','Le scénario propose de préparer les informations et actions décrites ci-dessous, avec les données et validations à confirmer.',profiles[id].result,'Cette étude décrit une proposition. Aucun déploiement ni gain mesuré n’est revendiqué.');
evidence('P074','Scénario proposé','La proposition retail décrit membres, identification QR ou code, historique, offres segmentées et suivi des usages. La connexion à la caisse reste à confirmer.','Un parcours de fidélité est proposé pour identifier les membres et suivre les avantages.','Un scénario de programme membre et de suivi des offres.','Le programme n’est pas présenté comme exploité ni comme ayant augmenté le réachat.');
evidence('P075','Scénario et maquette proposés','La proposition de restauration décrit commande directe, livraison, fidélité et assistant bilingue. Les connexions à la caisse et l’exploitation réelle ne sont pas prouvées.','Un parcours direct de commande et des services clients associés sont envisagés.','Une maquette et des scénarios à tester avec les outils du restaurant.','Les revenus et gains d’exploitation restent des objectifs à mesurer après une mise en service.');
evidence('P076','Prototype proposé','Le blueprint de production prévoit fiches de lots, pièces qualité, suivi et rapprochement avec des acheteurs. La démonstration utilise des données synthétiques.','Un prototype est conçu pour montrer comment relier informations de lot et critères acheteurs.','Des écrans de démonstration et scénarios de suivi.','La démonstration ne constitue ni une traçabilité exploitée en production, ni une certification, ni une transaction réalisée.');
evidence('P077','MVP proposé','Le cadrage de missions décrit disponibilités, pièces, contrats et rapprochement opérationnel. Les délais et gains annoncés comme objectifs ne sont pas repris comme des résultats.','Une vue de préparation des missions et dossiers administratifs est envisagée.','Un périmètre de prototype à tester avec une validation du responsable.','Les décisions d’affectation restent humaines. Aucune décision médicale n’est automatisée.');
evidence('P078','Audit réalisé','Un audit du site B2B a été réalisé avec observations techniques et recommandations de parcours. Les corrections n’ont pas été appliquées dans cette mission.','Les obstacles sont relevés et les actions recommandées sont priorisées.','Un audit et une feuille de corrections.','Le cas montre une analyse, pas une amélioration de conversion déjà obtenue.');
evidence('P079','Scénario proposé','La proposition e-commerce décrit catalogue, contenus et marketing multilingues. Aucun lancement ni résultat commercial n’est documenté.','Un plan de préparation des contenus et parcours est proposé.','Une proposition de périmètre et de contenus à tester.','Les statistiques de marché non sourcées et les gains non mesurés sont exclus du cas.');
evidence('P111','Prototype interne','Du code de démonstration pour réservations, tâches de chambres, factures et tableaux de bord est présent dans le projet interne. Aucun hôtel client ni exploitation réelle n’est établi.','Les écrans permettent de tester la circulation des informations entre les équipes.','Un prototype interne à évaluer sur des données de démonstration.','Les connexions et opérations réelles doivent être vérifiées avant une mise en service.');
const caseIntros={
 P052:'Distribution B2B : des traitements documentés pour retrouver les stocks, organiser le catalogue et préparer les contacts autour d’Odoo.',
 P053:'Plusieurs fichiers fournisseurs, une recherche de disponibilité : ce cas montre le rapprochement des références et la préparation d’un stock consolidé.',
 P054:'Pour préparer la prospection d’un distributeur B2B, les entreprises et leurs informations de qualification ont été réunies dans un tableau exploitable.',
 P055:'Les caractéristiques dispersées dans un catalogue B2B ont été organisées pour préparer des champs produits plus cohérents et plus faciles à utiliser.',
 P056:'Un catalogue B2B présentait des données à harmoniser. Un fichier de travail réunit les corrections proposées pour faciliter leur relecture.',
 P057:'Deux bases de contacts à comparer : ce cas présente les correspondances proposées et les exceptions, avant de décider des modifications du CRM.',
 P058:'Des contacts à créer ou à mettre à jour : des exports distincts préparent l’import CRM et permettent de vérifier les actions avant leur exécution.',
 P059:'Un site de recrutement aide ses prospects à comprendre leur besoin grâce à un quiz, un calculateur et un contact qui reprend leur contexte.',
 P060:'Sept questions aident le visiteur d’un site de recrutement à explorer une offre adaptée. L’orientation et son alternative sont expliquées.',
 P061:'Un calculateur de recrutement rend les postes de coût visibles pour aider le prospect à préparer son premier échange, avec des hypothèses explicites.',
 P062:'Des pages dédiées organisent les offres d’un acteur de services B2B pour aider le visiteur à comprendre ce qu’il peut demander.',
 P063:'Des sources techniques et une démarche de préparation de chapitres : ce cas explique comment faciliter l’assemblage et la relecture d’un manuel.',
 P064:'Un projet de prospection a nécessité de préparer les comptes et réglages email. Ce cas décrit les contrôles documentés avant utilisation.',
 P065:'Un scénario de portail propose de réunir statut, pièces et devis d’un dossier de diagnostic pour limiter les demandes de mise à jour.',
 P066:'Dans un site e-commerce multilingue, les parcours ont été ajustés pour orienter chaque public vers les pages et contacts qui le concernent.',
 P067:'Un projet interne documente une première publication de produit vérifiée. L’objectif est de réduire la préparation répétitive, avec une revue humaine.',
 P068:'Une préparation de migration multilingue organise pages, langues et contrôles pour anticiper les interruptions du parcours visiteur.',
 P069:'Un pilote marketing supervisé prépare des actions et les soumet à validation. Il sert à tester une tâche avant d’étendre le périmètre.',
 P070:'Une étude sport et textile identifie huit tâches à simplifier : achats, disponibilité, prix, prospection, contenus et suivi administratif.',
 P071:'Pour un équipementier, ce scénario propose de préparer les besoins d’achat et de réunir les disponibilités fournisseurs avant la décision de commande.',
 P072:'Deux offres, deux cibles : une étude distingue la préparation des contacts pour les clubs sportifs de celle des entreprises acheteuses de textile.',
 P073:'Une étude administrative propose de séparer les pièces par société et de préparer le suivi des échéances pour réduire classement et vérifications.',
 P074:'Un scénario retail propose une identification simple des membres et un suivi des avantages pour faciliter l’accueil et les actions de fidélité.',
 P075:'Une proposition de restauration réunit commandes directes, fidélité et assistance bilingue pour tester un parcours client plus simple.',
 P076:'Un prototype proposé réunit caractéristiques et pièces de lots, puis prépare des pistes acheteurs. L’équipe pourrait retrouver plus vite le contexte.',
 P077:'Un scénario de préparation des missions réunit disponibilités et pièces administratives pour faciliter le suivi par le responsable.',
 P078:'Un audit de site B2B relève les obstacles rencontrés par les visiteurs et donne des corrections à prioriser avant d’investir dans l’acquisition.',
 P079:'Une étude e-commerce propose d’organiser les contenus et parcours multilingues pour aider les acheteurs à retrouver les bonnes informations.',
 P111:'Un prototype interne d’hôtellerie teste le lien entre réservations et tâches de chambres pour aider les équipes à savoir quoi préparer.'
};
for(const [id,intro] of Object.entries(caseIntros))cases[id].intro=intro;
cases.P076.proof=cases.P076.proof.replace('Le blueprint de production prévoit','L’étude de production décrit');
cases.P076.action='L’étude décrit un prototype qui réunirait les informations d’un lot et préparerait les correspondances avec des besoins acheteurs.';
cases.P077.status='Prototype proposé';
Object.assign(cases.P063,{status:'Préparation documentée',proof:'Le dossier décrit une chaîne de préparation de chapitres à partir de sources techniques et un assemblage prévu en Word. Le fichier final annoncé n’a pas pu être confirmé dans les sources locales consultées.',action:'Les sources et étapes de préparation sont organisées pour produire des chapitres à relire et préparer leur assemblage.',result:'Une démarche documentée de préparation du manuel et de ses relectures.',limit:'Ce cas présente le travail de préparation. Il ne certifie ni la livraison finale du manuel, ni la validation du contenu technique par les experts.'});
profile('P105','W07',{intro:'Vous avez des contacts à créer et d’autres à mettre à jour ? Nous préparons deux listes d’actions, avec les champs proposés à relire, pour réduire les erreurs avant l’import.'});
profile('P106','W30',{intro:'Offrez à vos clients un parcours pour choisir leurs articles et préparer une commande auprès de vous. Votre équipe retrouve les informations utiles dans un format convenu.'});
profile('P108','W33',{intro:'Votre équipe doit retrouver les caractéristiques et les pièces d’un lot ? Nous les réunissons dans une fiche de suivi, avec les informations manquantes visibles.'});
profile('P110','W38',{intro:'Disponibilités, missions et pièces sont dispersées ? Nous préparons une vue commune pour que le responsable repère les dossiers à compléter et les prochaines actions.'});
export function coverage(inventory,pages){return inventory.workflows.map(w=>{const profile=byWorkflow[w.id];const ids=pages.filter(p=>profile.pageIds.includes(p.id)).map(p=>p.id);return {workflow:w.id,sourceStatus:w.status,pageIds:ids,commercialScope:['W08','W28','W29','W30','W31','W32','W33','W34','W35','W36','W37','W38','W45','W46'].includes(w.id)?'Cadrage et pilote sous conditions d’accès':'Mission définie à cadrer avec données et critères de réception',publicTitle:profile.title,qualification:profile.approval};});}
for(const [id,fields] of Object.entries(pageEdits)){if(!profiles[id])throw Error('Editorial page missing: '+id);Object.assign(profiles[id],fields);}
for(const [id,fields] of Object.entries(caseEdits)){if(!cases[id])throw Error('Editorial case missing: '+id);Object.assign(cases[id],fields);}
export {groups};
