// Illustrative inputs and outputs, tied to the documented workflow catalogue.
const rows=[
 ['W01','Stocks fournisseurs',['Fichiers de stock','Références Odoo'],'Disponibilités réunies','Date de la source','Référence inconnue'],
 ['W02','Liste de prospects',['Offre commerciale','Critères de ciblage'],'Entreprises retenues','Critères expliqués','Coordonnées incertaines'],
 ['W03','Caractéristiques produits',['Titres et descriptions','Champs du catalogue'],'Attributs structurés','Origine des valeurs','Champ manquant'],
 ['W04','Rédaction de fiches',['Données produits','Textes actuels'],'Textes proposés','Versions comparables','Publication à valider'],
 ['W05','Nettoyage du catalogue',['Fichier original','Règles de correction'],'Corrections proposées','Changements visibles','Ligne ambiguë'],
 ['W06','Rapprochement de contacts',['Première base','Seconde base'],'Correspondances proposées','Identifiants comparés','Fusion à confirmer'],
 ['W07','Import de contacts CRM',['Export existant','Format du CRM'],'Créations préparées','Mises à jour séparées','Import à valider'],
 ['W08','Demandes de couverture',['Dossiers disponibles','Réponses de l’organisme'],'Demandes suivies','Pièces en attente','Décision de couverture'],
 ['W09','Tailles et couleurs',['Modèles produits','Références de variantes'],'Déclinaisons organisées','Identifiants conservés','Variante à confirmer'],
 ['W10','Sources de stock',['Sources fournisseurs','Fréquence choisie'],'Fichiers récupérés','Date affichée','Source manquante'],
 ['W11','Comparaison de marges',['Coûts disponibles','Circuits de vente'],'Calculs comparables','Hypothèses visibles','Coût manquant'],
 ['W12','Catalogue commercial',['Produits retenus','Grille de prix'],'Sélection assemblée','Tarifs de la grille','Envoi à valider'],
 ['W13','Règles de prix Odoo',['Règles commerciales','Produits et clients'],'Tarifs calculés','Exceptions testées','Activation à valider'],
 ['W14','Préparation des achats',['Ventes et stocks','Commandes attendues'],'Besoins suggérés','Données du calcul','Commande à approuver'],
 ['W15','Vérification fournisseur',['Achats envisagés','Disponibilités accessibles'],'Références comparées','Indisponibilités repérées','Délai à confirmer'],
 ['W16','Prix revendeurs',['Coûts fournisseurs','Marges et arrondis'],'Grille recalculée','Règles appliquées','Diffusion à valider'],
 ['W17','Prospection clubs',['Disciplines et zone','Offre d’équipement'],'Clubs sélectionnés','Critères conservés','Destinataires à choisir'],
 ['W18','Prospection textile',['Offre textile','Activités ciblées'],'Entreprises segmentées','Critères conservés','Besoin à qualifier'],
 ['W19','Contenus produits',['Questions acheteurs','Caractéristiques fiables'],'Fiches proposées','Critères de choix','Publication à valider'],
 ['W20','Classement de factures',['Pièces reçues','Dossiers par société'],'Documents rangés','Doublons signalés','Attribution incertaine'],
 ['W21','Relances de factures',['Échéances','Paiements et litiges'],'Factures à traiter','Messages préparés','Statut à recontrôler'],
 ['W22','Pages de services',['Offres et périmètres','Questions des prospects'],'Pages organisées','Prestations expliquées','Engagements à valider'],
 ['W23','Questionnaire d’orientation',['Questions du quiz','Critères des offres'],'Orientation proposée','Explication affichée','Prestation à confirmer'],
 ['W24','Calculateur d’estimation',['Variables du calcul','Formules retenues'],'Estimation affichée','Hypothèses visibles','Devis distinct'],
 ['W25','Contact contextualisé',['Parcours du visiteur','Champs du formulaire'],'Demande préparée','Contexte choisi','Envoi par le visiteur'],
 ['W26','Manuel technique',['Documents sources','Plan des chapitres'],'Chapitres assemblés','Document éditable','Relecture par les experts'],
 ['W27','Infrastructure email',['Boîtes et domaine','Réglages email'],'Parcours de test','Authentification vérifiée','Campagne à autoriser'],
 ['W28','Suivi de dossiers',['Pièces du dossier','Rôles des intervenants'],'État consultable','Pièces manquantes','Décisions à prendre'],
 ['W29','Devis et notifications',['État du dossier','Règles de notification'],'Devis préparé','Événements identifiés','Envoi à confirmer'],
 ['W30','Commande directe',['Catalogue proposé','Parcours de commande'],'Commande préparée','Parcours à tester','Connexion à confirmer'],
 ['W31','Historique de fidélité',['Historique client','Règles commerciales'],'Avantages suivis','Données réunies','Offre à valider'],
 ['W32','Assistance bilingue',['Offre et questions','Deux langues'],'Réponses préparées','Contexte de commande','Exception à transmettre'],
 ['W33','Dossier de lot',['Caractéristiques du lot','Pièces disponibles'],'Informations réunies','Documents rattachés','Pièce à vérifier'],
 ['W34','Pistes acheteurs',['Lots disponibles','Critères de besoin'],'Correspondances possibles','Critères comparés','Qualification commerciale'],
 ['W35','Membres au comptoir',['Identifiant membre','Règles de fidélité'],'Membre retrouvé','Avantages suivis','Connexion caisse'],
 ['W36','Offres de fidélité',['Segments clients','Règles de campagne'],'Offres préparées','Utilisations suivies','Destinataires à choisir'],
 ['W37','Catalogue multilingue',['Catalogue source','Langues retenues'],'Versions préparées','Structure commune','Publication à valider'],
 ['W38','Dossiers de mission',['Disponibilités','Pièces administratives'],'Dossiers réunis','Disponibilités visibles','Affectation à décider'],
 ['W39','Audit du parcours',['Pages et liens','Offres et contact'],'Obstacles relevés','Corrections priorisées','Actions à décider'],
 ['W40','Routes multilingues',['Pages existantes','Langues et adresses'],'Parcours cohérents','Liens contrôlés','Pages à conserver'],
 ['W41','Parcours B2B et B2C',['Publics visés','Pages et contacts'],'Parcours distincts','Boutons adaptés','Orientation à vérifier'],
 ['W42','Publication de produits',['Données produits','Médias et contenus'],'Publication préparée','Étapes suivies','Sortie à contrôler'],
 ['W43','Traduction des pages',['Textes sources','Langues retenues'],'Versions préparées','Relecture organisée','Pages à contrôler'],
 ['W44','Migration de site',['Pages existantes','Parcours à garder'],'Plan de migration','Routes à vérifier','Bascule à confirmer'],
 ['W45','Assistant supervisé',['Sources autorisées','Tâche et règles'],'Actions proposées','Contexte conservé','Validation humaine'],
 ['W46','Réservations et chambres',['Données de démonstration','Rôles et tâches'],'Écrans à essayer','États consultables','Connexions à tester'],
 ['W47','Suivi d’automatisations',['Sorties attendues','Règles de contrôle'],'Résultats suivis','Problèmes signalés','Reprise à organiser']
];
export const taskScenes=Object.fromEntries(rows.map(([id,label,before,output,trace,review])=>[id,{label,before,after:output,rows:[['Préparation',output],['Suivi',trace],['À vérifier',review]],human:'Les décisions et les exceptions restent à votre équipe.'}]));
export const overviewScenes={
 P013:{label:'Choisir une première tâche',before:['Travail actuel','Exemples et fréquence'],after:'Une priorité à tester',rows:[['Tâche retenue','Besoin expliqué'],['Données nécessaires','À préparer'],['Premier test','Résultat défini']],human:'Le périmètre se choisit avec votre équipe.'},
 P052:{label:'Fichiers autour d’Odoo',before:['Stocks fournisseurs','Catalogue et contacts'],after:'Des fichiers de préparation',rows:[['Stocks','Disponibilités consolidées'],['Catalogue','Attributs à relire'],['Contacts','Imports à vérifier']],human:'Chaque traitement conserve son état de validation.'},
 P059:{label:'Parcours de recrutement',before:['Besoin du visiteur','Critères et hypothèses'],after:'Une demande contextualisée',rows:[['Quiz','Orientation expliquée'],['Calculateur','Estimation détaillée'],['Contact','Contexte choisi']],human:'L’équipe confirme l’offre lors de l’échange.'},
 P070:{label:'Choisir parmi huit scénarios',before:['Travail de l’équipementier','Données disponibles'],after:'Un premier scénario à tester',rows:[['Achats et prix','Données à comparer'],['Prospection','Cibles à préparer'],['Documents','Pièces à organiser']],human:'Illustration d’une proposition, à tester avec l’équipe.'},
 P072:{label:'Deux offres, deux prospections',before:['Équipements pour clubs','Textile pour entreprises'],after:'Des cibles à préparer par offre',rows:[['Clubs sportifs','Discipline et zone'],['Entreprises','Activité et usage'],['Destinataires','Choix du commercial']],human:'L’équipe confirme les besoins avant de proposer une gamme.'},
 P076:{label:'Lots et pistes acheteurs',before:['Caractéristiques et pièces','Critères acheteurs'],after:'Un dossier de lot à présenter',rows:[['Lot','Informations réunies'],['Pièces','Disponibilité à vérifier'],['Pistes acheteurs','À qualifier']],human:'Illustration d’un prototype proposé, sur données de démonstration.'}
};
