// Editorial descriptions grounded in the private inventory. Example situations are illustrative.
export const groups={operations:['Stocks, achats & prix','erp'],catalogue:['Catalogue & contenus','content'],commercial:['Prospection & ventes','sales'],admin:['Documents & administratif','admin'],experience:['Sites, parcours & fidélité','sales'],pilotage:['Portails & pilotage','care']};
import {workflowEdits} from './human-copy.mjs';
export const workflows=[];
function wf(id,pageIds,group,title,intro,today,action,result,benefit,example,steps,needs,approval){workflows.push({...{id,pageIds,group,title,intro,today,action,result,benefit,example,steps,needs,approval},...workflowEdits[id]});}
wf('W01',['P025','P053'],'operations','Voir les stocks de vos fournisseurs au même endroit',
 'Vos fournisseurs vous envoient chacun leur fichier de stock ? Nous les réunissons dans une liste lisible, reliée à vos références produits, pour que votre équipe sache ce qui est disponible.',
 'Vous ouvrez plusieurs fichiers, cherchez les références et recopiez les quantités. Une même référence peut avoir un nom différent selon le fournisseur.',
 'L’automatisation récupère les fichiers, reconnaît les produits et prépare une vue commune des disponibilités. Les références inconnues apparaissent dans une liste à vérifier.',
 'Une liste de disponibilités par produit et fournisseur, accompagnée des références à vérifier. Une mise à jour d’Odoo peut être ajoutée après validation du rapprochement.',
 ['Moins de recherche et de recopie avant de répondre à un client.','Une distinction claire entre votre stock et ce qu’un fournisseur peut livrer.','Les produits inconnus restent visibles au lieu de disparaître du fichier.'],
 ['Une question client, trois fichiers à ouvrir','Un client demande une disponibilité. Au lieu de consulter chaque fichier, votre commercial recherche votre référence dans la liste consolidée. Il voit les disponibilités par fournisseur et la date de la donnée. Si une référence n’est pas reconnue, elle part en vérification.'],
 [['Les fichiers arrivent','Nous récupérons les fichiers Excel, CSV ou les données accessibles chez vos fournisseurs.'],['Les produits sont rapprochés','Leurs références sont reliées à vos produits. Les lignes ambiguës sont mises à part.'],['Votre liste est prête','Votre équipe retrouve les disponibilités dans le fichier ou l’outil choisi.']],
 ['Des exemples de fichiers fournisseurs.','Votre liste de produits et de références.','Vos règles : stock détenu, stock fournisseur, délai et fréquence de mise à jour.'],
 'Votre équipe valide les correspondances inconnues et les règles de disponibilité avant toute écriture dans l’outil de gestion.');
wf('W02',['P036','P054'],'commercial','Donnez à vos commerciaux une liste de prospects à contacter',
 'Nous préparons une liste d’entreprises qui correspondent à votre cible, avec les informations utiles pour décider qui contacter. Vos commerciaux peuvent consacrer davantage de temps aux échanges.',
 'Votre équipe cherche des entreprises sur Internet, copie leurs informations et vérifie une par une si elles correspondent à votre offre.',
 'Nous transformons vos critères en recherches, regroupons les résultats et préparons une liste triée, avec les raisons de sélection et les informations encore à vérifier.',
 'Un tableau de prospects : entreprise, secteur, zone, informations de contact disponibles et critères de qualification.',
 ['Moins de temps consacré à constituer une liste.','Des cibles sélectionnées pour votre offre, plutôt qu’une base généraliste.','Une raison claire de contacter chaque entreprise.'],
 ['Trouver des distributeurs dans une nouvelle région','Vous définissez les produits, la zone et le type de distributeur recherché. Votre équipe reçoit une liste organisée, peut retirer les entreprises hors cible, puis choisir celles à contacter. Le tableau prépare la prospection ; il ne représente pas des ventes déjà obtenues.'],
 [['Définir la cible','Nous partons de vos bons clients et des critères qui les rendent pertinents.'],['Préparer la liste','Nous recherchons et regroupons les entreprises, en conservant l’origine des informations.'],['Choisir les contacts','Votre équipe vérifie les cibles prioritaires et décide de la campagne.']],
 ['Votre offre et quelques exemples de clients idéaux.','Les secteurs, zones et exclusions souhaités.','Les champs nécessaires à vos commerciaux.'],
 'Vous gardez le choix des cibles, du message et des envois. Une information de contact incertaine reste à vérifier.');
wf('W03',['P055'],'catalogue','Un catalogue produit que votre équipe peut vraiment exploiter',
 'Nous remettons vos caractéristiques produits dans les bons champs pour faciliter la recherche, les filtres et les mises à jour de votre catalogue.',
 'Les caractéristiques sont dispersées dans les descriptions. Les mêmes couleurs, matières ou dimensions sont écrites de plusieurs façons.',
 'Nous définissons les champs par famille de produits, classons les informations disponibles et préparons les données à intégrer.',
 'Un fichier structuré avec des colonnes cohérentes et les attributs manquants signalés.',
 ['Des produits plus faciles à rechercher et comparer.','Moins de corrections manuelles à chaque import.','Une base plus claire pour les filtres et les fiches produits.'],
 ['Retrouver tous les produits d’une même matière','La matière était parfois dans le titre, parfois dans la description. Elle est regroupée dans une colonne commune. Votre équipe peut filtrer cette colonne et voir quels produits demandent encore une vérification.'],
 [['Choisir les champs','Nous définissons les caractéristiques utiles à vos familles de produits.'],['Ranger les informations','Nous extrayons et harmonisons les données présentes dans vos sources.'],['Préparer l’intégration','Votre équipe relit un échantillon avant utilisation dans le catalogue.']],
 ['Un export du catalogue actuel.','Les caractéristiques que vos clients utilisent pour choisir.','Quelques fiches fournisseurs de référence.'],
 'Les caractéristiques absentes des sources restent à compléter. Votre équipe valide le fichier avant import.');
wf('W04',['P032'],'catalogue','Des fiches produits plus utiles, sans tout rédiger à la main',
 'Nous transformons vos caractéristiques réelles en titres, descriptions et informations de choix. Votre équipe reçoit des propositions à relire, prêtes à intégrer dans son catalogue.',
 'Les fiches sont courtes, répétitives ou incomplètes. Rédiger chaque description prend du temps et les informations utiles au client restent parfois cachées.',
 'Nous préparons des textes par famille de produits à partir des données disponibles, puis présentons les propositions à côté des contenus actuels.',
 'Des titres et descriptions proposés, les attributs utilisés et une vue avant/après pour choisir la version à publier.',
 ['Moins de rédaction répétitive pour votre équipe.','Des caractéristiques et usages plus faciles à comprendre pour l’acheteur.','Une relecture concentrée sur les différences et les informations importantes.'],
 ['Décrire une veste à partir de ses caractéristiques','La matière, la coupe et les tailles existent déjà dans votre catalogue. Nous les utilisons pour préparer une description lisible. Si une compatibilité ou une performance n’est pas documentée, elle n’est pas ajoutée au texte.'],
 [['Rassembler les informations','Nous identifions les attributs fiables et les informations manquantes.'],['Préparer les textes','Les descriptions suivent un format adapté à la famille de produits.'],['Relire et publier','Vous comparez les versions avant de choisir les contenus à intégrer.']],
 ['Un export de vos produits.','Vos fiches fournisseurs ou données techniques.','Votre ton et quelques fiches représentatives.'],
 'Vous validez les caractéristiques et la publication. La visibilité dans les moteurs de recherche se mesure après mise en ligne.');
wf('W05',['P030','P056'],'catalogue','Un catalogue plus propre, moins de corrections au quotidien',
 'Nous repérons les références en double, les formats incohérents et les champs incomplets pour préparer un catalogue plus facile à mettre à jour.',
 'Votre équipe corrige des majuscules, des unités et des catégories à chaque import. Des doublons ou des valeurs différentes passent dans le catalogue.',
 'Nous appliquons des règles de nettoyage convenues avec vous et séparons les corrections certaines des lignes à revoir.',
 'Un fichier nettoyé, un relevé des changements et une liste des cas qui demandent une décision.',
 ['Moins de petites corrections répétées à chaque mise à jour.','Des catégories et formats cohérents pour votre équipe.','Les changements sont lisibles avant de toucher au catalogue.'],
 ['Trois écritures pour une même taille','Le fichier mélange « XL », « X-Large » et « xl ». Après validation de votre règle, une seule valeur est proposée. Une taille inconnue reste dans la liste de vérification.'],
 [['Repérer les écarts','Nous recherchons doublons, champs vides et valeurs incohérentes.'],['Préparer les corrections','Les règles simples sont appliquées et les changements expliqués.'],['Valider le fichier','Un échantillon est relu avant l’import ou la mise à jour.']],
 ['Votre export produit.','Les formats et valeurs souhaités.','Les champs qui doivent rester inchangés.'],
 'Vous approuvez les règles et les corrections ambiguës. Le fichier original est conservé.');
wf('W06',['P034','P057'],'commercial','Retrouvez les bons clients entre vos deux logiciels',
 'Nous comparons vos bases clients pour retrouver les entreprises présentes dans les deux outils, repérer les doublons et mettre de côté les correspondances incertaines.',
 'Une même entreprise a un nom différent dans chaque outil. Votre équipe cherche les correspondances avant un transfert ou une mise à jour.',
 'Nous comparons les identifiants disponibles, puis préparons les correspondances avec leurs raisons. Les rapprochements ambigus sont isolés.',
 'Un tableau distinguant les correspondances fiables, les entreprises non retrouvées et les cas à vérifier.',
 ['Moins de recherches manuelles entre les bases clients.','Une préparation plus claire avant de créer ou modifier des contacts.','Les rapprochements incertains restent sous votre contrôle.'],
 ['Deux noms, une même entreprise','Une société apparaît avec sa raison sociale dans un logiciel et son nom commercial dans l’autre. Un identifiant commun permet de la rapprocher. Si le nom est le seul indice, la correspondance vous est proposée pour vérification.'],
 [['Exporter les bases','Nous rassemblons les champs utiles dans les deux outils.'],['Comparer les identifiants','Les correspondances sont classées selon les informations disponibles.'],['Relire les exceptions','Votre équipe décide des cas incertains avant les modifications.']],
 ['Les exports des deux bases clients.','Les identifiants disponibles : numéro d’entreprise, email, téléphone ou adresse.','La règle qui désigne la donnée à conserver.'],
 'Votre équipe valide les fusions et les mises à jour. Une ressemblance de nom ne déclenche pas seule une modification.');
wf('W07',['P058','P105'],'commercial','Préparez votre import CRM sans tout ressaisir',
 'Nous transformons un fichier de contacts en une liste de créations et de mises à jour prête à vérifier. Votre équipe sait ce qui sera ajouté ou changé avant l’import.',
 'Les colonnes du fichier ne correspondent pas à votre CRM. Vous devez séparer les nouveaux contacts, vérifier ceux qui existent déjà et corriger les données.',
 'Nous rangeons les données dans le format attendu, distinguons créations et mises à jour et signalons les champs incomplets.',
 'Des fichiers d’import séparés, une liste des changements proposés et les lignes à compléter.',
 ['Moins de ressaisie lors de l’ajout de contacts.','Une distinction nette entre nouveau contact et contact existant.','Une vérification possible avant de modifier la base commerciale.'],
 ['Importer une liste issue d’un salon','Une partie des entreprises existe déjà dans votre CRM. Le fichier préparé distingue les nouvelles fiches et les champs à mettre à jour. Les contacts sans information suffisante restent hors de l’import validé.'],
 [['Définir le format','Nous identifions les champs obligatoires du CRM.'],['Préparer les fichiers','Les créations et mises à jour sont séparées.'],['Tester un échantillon','Votre équipe vérifie quelques fiches avant l’import complet.']],
 ['La liste à importer.','Un export des contacts existants.','Le format d’import et les champs obligatoires du CRM.'],
 'L’import est lancé après validation du fichier et d’un test.');
wf('W08',['P042'],'admin','Suivez vos demandes de couverture crédit sans perdre le fil',
 'Nous pouvons réunir les demandes, leurs statuts et les prochaines actions dans un suivi commun. Votre responsable garde la décision et les échanges avec l’organisme concerné.',
 'Les demandes sont suivies dans des emails et des fichiers différents. Il devient difficile de voir ce qui attend une réponse ou une pièce.',
 'Après vérification des accès disponibles, nous préparons un suivi des demandes et des rappels sur les dossiers incomplets.',
 'Un tableau de suivi des dossiers, des pièces attendues et des dates de relance.',
 ['Moins de recherches dans les échanges pour retrouver un statut.','Une meilleure visibilité sur les dossiers en attente.','Des relances préparées sans automatiser une décision de crédit.'],
 ['Une demande reste sans réponse','Le dossier apparaît « réponse attendue » avec sa dernière date de suivi. Votre responsable retrouve les pièces et décide de relancer. L’outil ne confirme aucune couverture à la place de l’organisme.'],
 [['Identifier les données','Nous vérifions les exports et accès possibles.'],['Organiser le suivi','Les dossiers, statuts et pièces sont réunis.'],['Préparer les rappels','Les actions à faire sont présentées au responsable.']],
 ['Vos étapes de traitement et statuts.','Des exemples de demandes anonymisées.','Les accès ou exports autorisés par votre prestataire.'],
 'Le responsable confirme les montants, réponses et décisions. Ce service commence par une étude de faisabilité des accès.');
wf('W09',['P031'],'catalogue','Des tailles, couleurs et références qui ne se mélangent plus',
 'Nous structurons les variantes de vos produits pour que chaque combinaison de taille, couleur ou modèle corresponde à une référence identifiable.',
 'Les mêmes produits existent sous plusieurs lignes ou noms. Une taille peut être mal rattachée et compliquer les commandes ou le suivi de stock.',
 'Nous préparons les familles de produits, les variantes et les règles de références à partir de votre catalogue.',
 'Une structure de produits et de variantes, avec les correspondances et les créations proposées.',
 ['Des commandes plus faciles à relier au bon produit.','Un suivi du stock par taille ou couleur plus lisible.','Moins de travail manuel pour créer des déclinaisons cohérentes.'],
 ['Une veste vendue en plusieurs tailles et couleurs','Le modèle est regroupé sous une famille. Chaque combinaison disponible reçoit sa référence. Une combinaison absente de vos sources reste à confirmer avant création.'],
 [['Identifier les combinaisons','Nous recensons modèles, tailles, couleurs et codes.'],['Préparer la structure','Les variantes sont regroupées et reliées au produit principal.'],['Valider les références','Vous relisez les créations avant leur import.']],
 ['Le catalogue et les références actuelles.','Les tailles, couleurs ou dimensions utilisées.','Vos règles de création de références.'],
 'Vous validez la structure et les nouveaux produits avant toute création.');
wf('W10',['P027'],'operations','Gardez vos disponibilités fournisseurs à jour',
 'Nous organisons la récupération régulière des disponibilités fournisseurs pour éviter que votre équipe travaille avec un ancien fichier de stock.',
 'Un fichier est mis à jour sans que tout le monde le sache. Un commercial peut consulter une disponibilité qui ne correspond plus à la dernière source.',
 'Nous récupérons les sources à la fréquence convenue, vérifions leur date et préparons les disponibilités dans votre outil ou fichier de travail.',
 'Une vue de disponibilités actualisée, une date de mise à jour et un signalement des sources manquantes.',
 ['Moins de téléchargements et de vérifications manuelles.','La date de la disponibilité est visible avant de répondre au client.','Un fournisseur indisponible est signalé plutôt que remplacé par une ancienne donnée silencieuse.'],
 ['Un fournisseur n’envoie pas son fichier habituel','La source manquante est signalée. Votre équipe voit quelles disponibilités ont été actualisées et lesquelles nécessitent une vérification avant confirmation au client.'],
 [['Définir le rythme','Nous identifions quand les sources sont réellement mises à jour.'],['Récupérer les données','Les fichiers ou connexions autorisés sont lus régulièrement.'],['Afficher la fraîcheur','La dernière mise à jour et les erreurs de source sont visibles.']],
 ['Les fichiers ou connexions fournisseurs disponibles.','La fréquence réelle de mise à jour des sources.','L’outil dans lequel votre équipe consulte les disponibilités.'],
 'Votre équipe définit ce qui peut être affiché ou confirmé lorsqu’une source manque.');
wf('W11',['P104'],'operations','Comparez vos marges avec les vrais coûts de chaque circuit',
 'Nous préparons une comparaison des prix, achats et frais par circuit de vente ou de livraison. Vous voyez où une même vente change de marge selon son parcours.',
 'Le prix d’achat est connu, mais le transport ou d’autres frais sont ajoutés dans plusieurs fichiers. Comparer les circuits demande des calculs répétés.',
 'Nous rassemblons les coûts que vous retenez et appliquons votre règle de calcul pour comparer les scénarios.',
 'Un tableau de marges calculées par circuit, avec le détail des coûts utilisés et les données manquantes.',
 ['Moins de calculs répétés pour comparer plusieurs parcours.','Les frais pris en compte restent visibles dans le résultat.','Des décisions tarifaires appuyées sur votre méthode de calcul.'],
 ['Vendre le même produit par deux circuits','Vous comparez deux circuits avec des frais de transport différents. Le tableau affiche pour chacun les coûts retenus et la marge calculée. Une charge inconnue est signalée au lieu d’être devinée.'],
 [['Définir les coûts','Vous choisissez les frais à inclure et leur source.'],['Calculer les scénarios','Les règles sont appliquées par produit et circuit.'],['Comparer les résultats','Votre équipe relit les coûts et les écarts.']],
 ['Les coûts d’achat et frais par circuit.','Vos prix de vente.','La méthode de calcul validée par votre responsable.'],
 'Votre responsable valide la méthode et les coûts. Le tableau ne remplace pas une validation comptable.');
wf('W12',['P033'],'commercial','Préparez un catalogue adapté à chaque client B2B',
 'Nous assemblons les produits, prix et informations utiles à un client dans un catalogue personnalisé, à partir de vos données validées.',
 'Votre équipe copie des images et des prix pour préparer chaque document commercial. Une mise à jour du catalogue oblige à refaire plusieurs fichiers.',
 'Nous appliquons vos règles de sélection de produits et de prix pour préparer le document au format convenu.',
 'Un catalogue commercial préparé pour un segment ou un client, avec la sélection et les prix utilisés.',
 ['Moins de mise en page répétitive avant une proposition commerciale.','Une sélection de produits adaptée au destinataire.','Des prix reliés à une source validée.'],
 ['Un revendeur ne veut qu’une gamme précise','Vous choisissez sa gamme et sa grille de prix. Le document ne reprend que les références concernées. Votre commercial relit les prix avant de l’envoyer.'],
 [['Choisir la sélection','Nous définissons les produits et informations à afficher.'],['Assembler le catalogue','Les textes, visuels disponibles et prix sont repris depuis vos sources.'],['Relire le document','Votre équipe contrôle la version destinée au client.']],
 ['Le catalogue produit et les images autorisées.','Les grilles de prix par destinataire.','Le format commercial souhaité.'],
 'Votre équipe valide les produits, les prix et la diffusion du document.');
wf('W13',['P029'],'operations','Appliquez vos règles de prix sans gérer chaque tarif à la main',
 'Nous organisons vos règles de prix dans Odoo pour préparer les tarifs par type de client, gamme ou condition commerciale.',
 'Les exceptions tarifaires s’accumulent. Votre équipe doit modifier plusieurs listes pour une même évolution de coût ou de règle.',
 'Nous traduisons vos règles dans une structure de listes de prix, puis préparons des tests sur les produits et clients concernés.',
 'Une structure de tarification et des exemples de prix calculés pour vérifier le résultat avant application.',
 ['Moins de modifications manuelles dispersées entre les listes.','Des règles tarifaires plus faciles à expliquer et maintenir.','Une vérification sur les cas clients avant activation.'],
 ['Une nouvelle règle pour vos revendeurs','Vous définissez une remise ou une marge sur une gamme. Les prix proposés sont testés pour plusieurs types de clients et exceptions avant d’activer la règle.'],
 [['Recenser les règles','Nous listons conditions générales et exceptions.'],['Préparer la structure','Les règles sont traduites dans les listes de prix disponibles.'],['Tester les tarifs','Votre équipe vérifie des paniers et clients représentatifs.']],
 ['Vos règles tarifaires actuelles.','La version et les modules Odoo concernés.','Des exemples d’exceptions commerciales.'],
 'Votre responsable commercial valide les prix et les exceptions avant activation.');
wf('W14',['P026','P071'],'operations','Préparez vos achats avec les ventes, le stock et les reliquats',
 'Nous réunissons vos ventes, stocks et commandes en attente pour préparer une liste d’achats à vérifier. Votre équipe garde la décision de commander.',
 'Les besoins sont répartis entre ventes passées, stock disponible et commandes non livrées. Préparer un achat demande plusieurs comparaisons.',
 'Nous rapprochons ces informations par modèle et taille, puis appliquons vos règles pour préparer les quantités proposées.',
 'Une liste de commandes suggérées avec les ventes, stocks et reliquats qui expliquent chaque proposition.',
 ['Moins de tableaux à comparer pour préparer un achat.','Les commandes en attente sont prises en compte dans la suggestion.','Votre équipe voit la raison de chaque quantité avant de commander.'],
 ['Préparer la prochaine commande d’une gamme textile','Pour chaque taille, le tableau réunit les ventes, le stock restant et les quantités déjà attendues. Votre acheteur peut corriger la suggestion avant de confirmer la commande au fournisseur.'],
 [['Réunir les données','Nous récupérons ventes, stock et commandes non soldées.'],['Préparer les besoins','Les règles d’achat sont appliquées par référence et variante.'],['Valider la commande','L’acheteur contrôle les quantités et les disponibilités fournisseurs.']],
 ['Les ventes et stocks par référence.','Les commandes et reliquats en cours.','Vos seuils ou règles de préparation des achats.'],
 'Chaque commande reste approuvée par votre acheteur. Les suggestions dépendent de la qualité et de la fraîcheur des données.');
wf('W15',['P027','P071'],'operations','Tenez compte de la disponibilité fournisseur dans vos achats',
 'Nous relions vos besoins d’achat aux données de disponibilité accessibles chez les fournisseurs pour préparer une commande que votre acheteur peut vérifier.',
 'Votre équipe prépare une commande, puis découvre que certaines tailles ou références ne sont plus disponibles.',
 'Nous comparons les besoins calculés aux disponibilités connues et isolons les produits qui demandent une confirmation fournisseur.',
 'Une préparation d’achat distinguant références disponibles, informations manquantes et demandes de confirmation.',
 ['Les indisponibilités connues sont visibles avant validation de l’achat.','Moins de vérifications répétées par modèle et taille.','Une liste claire des points à confirmer au fournisseur.'],
 ['Une taille est manquante chez le fournisseur','La préparation d’achat la signale et conserve le besoin client. L’acheteur peut demander un délai ou choisir une autre option, au lieu de considérer la commande comme déjà confirmée.'],
 [['Lire les besoins','Les références et quantités souhaitées sont préparées.'],['Comparer les disponibilités','Les données accessibles du fournisseur sont rapprochées.'],['Présenter les exceptions','Les produits indisponibles ou non renseignés sont signalés.']],
 ['La préparation d’achat.','Des disponibilités fournisseurs accessibles et datées.','Les correspondances de références et de tailles.'],
 'L’acheteur confirme les délais et les commandes. Un stock fournisseur affiché ne vaut pas une réservation.');
wf('W16',['P028'],'operations','Calculez vos prix revendeurs sans refaire les mêmes tableaux',
 'Nous préparons vos prix à partir des coûts et règles de marge que vous choisissez. Votre équipe reçoit une grille à vérifier avant diffusion.',
 'Un coût change et vous devez recalculer plusieurs prix. Les remises et exceptions sont parfois conservées dans des fichiers séparés.',
 'Nous rassemblons les coûts, appliquons les règles par famille ou client et signalons les produits sans information suffisante.',
 'Une grille de prix calculés, les coûts utilisés et les exceptions à valider.',
 ['Moins de calculs manuels lors d’un changement fournisseur.','Une règle cohérente entre les produits concernés.','Les exceptions commerciales restent visibles avant diffusion.'],
 ['Mettre à jour une grille après une hausse fournisseur','Les nouveaux coûts sont rapprochés de vos références. La grille affiche les prix proposés selon votre règle. Un produit sans coût confirmé reste à compléter avant d’envoyer le document aux revendeurs.'],
 [['Rassembler les coûts','Nous identifions la source d’achat et les frais retenus.'],['Calculer les prix','Vos règles de marge, remise et arrondi sont appliquées.'],['Relire la grille','Le responsable confirme les exceptions avant diffusion.']],
 ['Les coûts et frais que vous souhaitez inclure.','Vos règles de marge, de remise et d’arrondi.','La liste des produits et conditions revendeurs.'],
 'Vous choisissez les règles et validez la grille. Nous n’inventons pas les coûts manquants.');
wf('W17',['P037'],'commercial','Préparez une prospection adaptée aux clubs sportifs',
 'Nous organisons une liste de clubs pertinents pour votre offre et les informations utiles à votre commercial : discipline, zone et contact disponible.',
 'Votre équipe cherche les clubs, recopie les coordonnées et essaie de distinguer ceux auxquels l’offre pourrait être utile.',
 'Nous appliquons vos critères de discipline et de zone, structurons les résultats et préparons la segmentation commerciale.',
 'Une liste de clubs et un classement par segment, avec les informations à vérifier avant contact.',
 ['Moins de recherche manuelle avant une campagne.','Une cible cohérente avec vos équipements et votre zone commerciale.','Un message qui peut être adapté à la discipline et au besoin du club.'],
 ['Proposer des équipements aux clubs de badminton','La liste cible cette discipline dans votre zone. Le commercial retrouve les clubs sélectionnés et les informations disponibles. Il valide les contacts et le message avant de lancer la campagne.'],
 [['Définir les clubs visés','Vous précisez discipline, zone et type de besoin.'],['Préparer la liste','Les clubs sont regroupés et classés.'],['Préparer le contact','Votre équipe valide les destinataires et la proposition.']],
 ['Les équipements ou offres à proposer.','Les disciplines et zones recherchées.','Vos exclusions et règles de contact.'],
 'Votre équipe choisit les destinataires et approuve les envois. Une liste de clubs n’est pas un résultat de vente.');
wf('W18',['P038'],'commercial','Trouvez des entreprises pertinentes pour votre offre textile',
 'Nous préparons une liste d’entreprises dont l’activité correspond à votre offre de textile professionnel ou personnalisé, puis les classons pour votre prospection.',
 'Une liste généraliste mélange des entreprises qui ont des besoins très différents. Votre commercial passe du temps à faire le tri.',
 'Nous définissons les segments et les critères de pertinence, puis préparons les entreprises et informations à vérifier.',
 'Un fichier segmenté d’entreprises, avec leur activité et les éléments qui expliquent leur sélection.',
 ['Moins de tri dans une base commerciale généraliste.','Des segments utiles pour adapter la proposition textile.','Une préparation claire pour les premiers échanges commerciaux.'],
 ['Une offre de vêtements pour équipes terrain','Vous ciblez des entreprises dont les salariés travaillent sur le terrain. La liste distingue les secteurs retenus. Le commercial confirme le besoin réel avant de proposer une gamme ou une personnalisation.'],
 [['Préciser l’offre','Nous distinguons textile professionnel, événementiel et personnalisé.'],['Sélectionner les entreprises','Les critères sont appliqués aux sources accessibles.'],['Organiser les segments','Votre équipe retrouve des groupes exploitables pour la campagne.']],
 ['Votre catalogue et votre offre textile.','Les activités et zones souhaitées.','Les critères d’exclusion et champs commerciaux utiles.'],
 'Le commercial vérifie le besoin et décide du message. Aucun besoin d’achat n’est supposé acquis.');
wf('W19',['P016'],'catalogue','Aidez vos clients à choisir avec des contenus produits plus clairs',
 'Nous préparons des fiches qui répondent aux questions de vos acheteurs à partir de vos données produit. Votre équipe relit les propositions avant publication.',
 'Les descriptions reprennent les textes fournisseurs sans expliquer clairement les différences et usages utiles à votre client.',
 'Nous définissons un format par famille, préparons les textes et organisons leur comparaison avec les contenus actuels.',
 'Des fiches proposées et un format réutilisable pour les prochaines références.',
 ['Moins de rédaction répétitive lors de l’ajout de produits.','Des réponses plus lisibles aux questions des acheteurs.','Des contenus reliés aux caractéristiques que vous pouvez vérifier.'],
 ['Expliquer la différence entre deux références','Les caractéristiques connues permettent de préparer les critères de choix. Le client lit les différences utiles. Une performance absente des sources n’est pas inventée pour rendre la fiche plus persuasive.'],
 [['Lister les questions clients','Nous partons des informations que vos acheteurs cherchent.'],['Préparer les contenus','Les textes utilisent les attributs disponibles.'],['Relire les fiches','Votre équipe confirme les informations avant publication.']],
 ['Le catalogue et les sources techniques.','Les questions fréquentes de vos clients.','Le ton et le format souhaités.'],
 'Vous validez les informations et les publications. Aucun classement ou citation par un moteur IA n’est garanti.');
wf('W20',['P040','P073'],'admin','Retrouvez vos factures dans le bon dossier, sans les classer une par une',
 'Nous organisons le traitement des factures reçues par email : identifier la bonne société, ranger la pièce et préparer sa transmission à la comptabilité.',
 'Votre équipe ouvre les pièces jointes, cherche à quelle société elles appartiennent, les renomme et les déplace dans les dossiers.',
 'L’automatisation lit les informations disponibles, prépare le nom et le classement, puis met à part les pièces douteuses ou déjà reçues.',
 'Des pièces rangées dans les dossiers convenus, une liste des documents traités et les pièces qui demandent une vérification.',
 ['Moins de manipulation de pièces jointes au quotidien.','Des documents plus faciles à retrouver par société et période.','Une préparation plus simple pour la transmission comptable.'],
 ['Une facture arrive dans la boîte d’une société','La pièce est identifiée et rangée dans le dossier prévu. Si la société ou le numéro n’est pas clair, elle reste à vérifier. Un document déjà traité est signalé pour éviter un double classement.'],
 [['Recevoir la pièce','Nous lisons les documents de la boîte autorisée.'],['Identifier et ranger','La société, le fournisseur et la période servent au classement.'],['Vérifier les exceptions','Votre équipe traite les pièces qui demandent une décision.']],
 ['Une boîte email et des dossiers par société.','Des exemples de factures et frais généraux.','Les règles de nommage et de transmission comptable.'],
 'Votre équipe garde la validation comptable et les pièces incertaines. Le classement ne déclenche pas de paiement.');
wf('W21',['P041'],'admin','Gardez vos factures en retard dans le radar',
 'Nous préparons le suivi des échéances et les relances selon vos règles, pour que votre équipe sache qui relancer et quelles factures demandent une vérification.',
 'Les échéances sont suivies dans plusieurs fichiers. Préparer les messages demande de vérifier les paiements et les litiges un par un.',
 'Nous comparons échéance, paiement et litige, puis préparons les rappels et le message adapté au niveau de retard.',
 'Une liste de factures à traiter, des relances préparées et un historique des actions prévues ou validées.',
 ['Moins d’oublis dans le suivi des échéances.','Moins de préparation manuelle des messages de relance.','Les factures payées ou contestées sont exclues selon vos règles.'],
 ['Une facture dépasse son échéance','Le statut de paiement est recontrôlé. Si elle reste ouverte et sans litige, une relance est préparée. Votre équipe valide le message ou active uniquement les envois répondant aux règles convenues.'],
 [['Lire les statuts','Nous récupérons les échéances et informations de paiement.'],['Préparer les actions','Les règles choisissent rappel, relance ou vérification.'],['Garder la trace','Les messages et décisions sont enregistrés pour le suivi.']],
 ['Les factures et leurs échéances.','Une source de paiement suffisamment à jour.','Vos messages, délais de relance et règles de litige.'],
 'Vous approuvez la séquence et les exceptions. Une facture payée ou contestée ne doit pas recevoir une relance inappropriée.');
wf('W22',['P062'],'experience','Des pages qui aident votre prospect à comprendre votre offre',
 'Nous organisons vos pages de services autour des besoins clients, des prestations proposées et de la prochaine étape pour vous contacter.',
 'Votre site décrit votre entreprise, mais un visiteur doit encore chercher quel service correspond à son problème.',
 'Nous séparons les offres, clarifions leurs bénéfices et relions chaque page aux exemples et au bon contact.',
 'Des pages de services et des contenus organisés autour des questions de vos prospects.',
 ['Une offre plus facile à comprendre dès la première visite.','Des questions récurrentes traitées avant le premier échange.','Un parcours plus direct vers une demande pertinente.'],
 ['Un prospect hésite entre deux prestations','Les pages lui expliquent à qui chaque offre s’adresse, ce qu’elle comprend et les informations à fournir. Il arrive au contact avec un besoin mieux exprimé.'],
 [['Clarifier les besoins','Nous relevons les questions posées à vos commerciaux.'],['Organiser les offres','Chaque prestation reçoit une explication et des exemples adaptés.'],['Relier au contact','Le visiteur trouve une prochaine étape cohérente avec son besoin.']],
 ['Vos offres actuelles.','Les questions fréquentes des prospects.','Des exemples de prestations et résultats documentés.'],
 'Vous validez les engagements commerciaux et les contenus avant publication.');
wf('W23',['P043','P060'],'experience','Aidez votre prospect à trouver le service qui lui correspond',
 'Nous concevons un questionnaire court qui oriente le visiteur vers une offre pertinente et transmet son contexte à votre équipe commerciale.',
 'Le visiteur ne connaît pas vos catégories de services. Il vous contacte avec une demande vague, ou quitte le site sans choisir.',
 'Nous posons les questions utiles, appliquons votre grille de choix et expliquons le résultat proposé.',
 'Un quiz métier, une recommandation expliquée et un accès au contact avec le contexte du besoin.',
 ['Une première orientation accessible sans connaître votre métier.','Des demandes mieux renseignées pour vos commerciaux.','Moins de questions à reprendre au début de chaque échange.'],
 ['Un employeur cherche une solution de recrutement','Le quiz demande urgence, durée et volume du besoin. Le résultat propose un point de départ et une alternative. Le commercial confirme ensuite le choix selon le contexte réel.'],
 [['Choisir les questions','Nous retenons celles qui changent réellement la recommandation.'],['Définir les réponses','Les règles de choix sont expliquées et testées.'],['Transmettre le besoin','Le contact reprend le contexte utile au commercial.']],
 ['Vos offres et critères de choix.','Les questions que pose votre équipe.','Le formulaire ou circuit de contact existant.'],
 'Votre équipe confirme la recommandation. Le quiz fournit une orientation, pas un engagement commercial automatique.');
wf('W24',['P044','P061'],'experience','Rendez un coût ou un scénario facile à comprendre',
 'Nous construisons un calculateur qui permet au visiteur d’explorer une estimation avec ses propres hypothèses et de demander un échange avec le résultat.',
 'Vos prospects ont du mal à comprendre les éléments d’un coût. Les commerciaux refont les mêmes calculs pour expliquer différents scénarios.',
 'Nous rendons les hypothèses visibles et traduisons votre méthode de calcul dans un outil accessible sur votre site.',
 'Un calculateur, un résultat expliqué et un contact qui reprend le scénario choisi.',
 ['Une discussion commerciale appuyée sur des hypothèses partagées.','Moins de calculs répétitifs pendant les premiers échanges.','Un visiteur qui comprend mieux les facteurs du coût.'],
 ['Comprendre le coût de préparation d’un recrutement','Le visiteur renseigne poste, nombre de recrutements et effort interne. L’outil détaille les postes de coût selon la méthode convenue. Le résultat reste une estimation, distincte du devis de votre entreprise.'],
 [['Définir la méthode','Vous validez variables, formules et limites.'],['Construire l’outil','Les champs et résultats sont présentés avec leurs hypothèses.'],['Relier à l’échange','Le prospect peut transmettre son scénario à votre commercial.']],
 ['Une méthode de calcul explicite.','Les variables et limites utiles.','Votre parcours de contact.'],
 'Vous validez les formules et les hypothèses. Une estimation n’est pas un devis.');
wf('W25',['P045'],'experience','Recevez des demandes avec le contexte du visiteur',
 'Nous faisons suivre la page, le service ou le résultat consulté dans le formulaire de contact, pour que votre équipe comprenne plus vite la demande.',
 'Le prospect remplit un formulaire généraliste. Votre équipe ignore l’article, l’offre ou la simulation qui a motivé sa demande.',
 'Nous relions les boutons de contact au formulaire existant et transmettons les informations utiles au bon destinataire.',
 'Un formulaire contextualisé et une demande qui indique le service ou scénario concerné.',
 ['Moins d’informations à redemander au prospect.','Une préparation plus rapide du premier échange.','Une meilleure lecture des pages qui génèrent des demandes.'],
 ['Un visiteur contacte après un calculateur','Son message peut reprendre le scénario qu’il souhaite partager. Le commercial sait quel besoin a été exploré avant l’appel. Les informations privées ne sont pas ajoutées aux événements de mesure.'],
 [['Identifier le contexte','Nous choisissons les informations utiles au destinataire.'],['Relier les parcours','Les boutons et formulaires reprennent ce contexte.'],['Vérifier la réception','Le parcours est testé jusqu’à la réception convenue.']],
 ['Votre formulaire et ses destinataires.','Les pages ou outils à relier.','Les champs utiles à votre équipe.'],
 'Le visiteur choisit les informations qu’il transmet. La mesure des parcours doit éviter les données personnelles dans ses libellés.');
wf('W26',['P048','P063'],'admin','Transformez vos documents sources en un manuel organisé',
 'Nous préparons un document structuré à partir de vos PDF et sources techniques, pour que vos experts passent davantage de temps à vérifier le fond qu’à assembler les pages.',
 'Les informations sont dispersées entre plusieurs PDF. Extraire, organiser et mettre en forme les chapitres prend beaucoup de temps.',
 'Nous organisons les sources par thème, préparons les chapitres et assemblons un document éditable avec les points à relire.',
 'Un document Word structuré, les références de sources et les éléments à vérifier par vos experts.',
 ['Moins d’assemblage manuel entre les documents sources.','Une structure commune pour les chapitres.','Une relecture organisée pour les personnes qui connaissent le sujet.'],
 ['Préparer un support de formation à partir de PDF','Les sources sont regroupées par chapitre. Un brouillon organisé est préparé et les points incertains sont remontés à l’expert. Après relecture, les chapitres sont assemblés dans le document final.'],
 [['Organiser les sources','Les documents sont classés selon le plan retenu.'],['Préparer les chapitres','Les informations sont structurées avec leurs références.'],['Assembler après relecture','Les experts confirment les passages avant la version finale.']],
 ['Les documents que vous êtes autorisé à utiliser.','Le plan et le public du manuel.','Un expert disponible pour vérifier le contenu.'],
 'Vos experts valident les informations techniques. La production du document ne constitue pas une certification.');
wf('W27',['P039','P064'],'commercial','Préparez une base email fiable avant vos campagnes',
 'Nous vérifions les domaines, boîtes et outils nécessaires à vos campagnes, puis testons le parcours avant de préparer une montée en charge adaptée.',
 'Une campagne est prête, mais les boîtes ou réglages du domaine n’ont pas été vérifiés. Un problème d’envoi peut être découvert après le lancement.',
 'Nous organisons les accès, l’authentification des emails et les tests d’envoi, puis définissons le suivi avec vous.',
 'Des réglages et tests documentés, les limites identifiées et un plan de préparation des campagnes.',
 ['Les problèmes de configuration sont repérés avant les envois à grande échelle.','Vos équipes savent quels outils et boîtes utiliser.','La montée en charge suit un plan plutôt qu’un lancement improvisé.'],
 ['Préparer une nouvelle boîte commerciale','Un message test permet de vérifier la réception et l’identité de l’expéditeur. Les réglages manquants sont corrigés avant de préparer la cadence de la campagne.'],
 [['Vérifier les accès','Nous identifions domaines, boîtes et outils d’envoi.'],['Tester les messages','La réception et les réglages sont vérifiés sur un parcours de test.'],['Préparer la cadence','Le suivi et les limites d’envoi sont définis.']],
 ['Les accès autorisés au domaine et aux boîtes.','Votre outil d’envoi.','Votre cible, messages et volumes envisagés.'],
 'Vous validez les campagnes et destinataires. Les tests ne garantissent pas la réception de tous les messages futurs.');
wf('W28',['P047','P065'],'pilotage','Suivez chaque dossier sans chercher dans les emails',
 'Nous concevons un portail qui réunit statut, pièces et prochaines actions d’un dossier. Chaque personne voit les informations utiles à son rôle.',
 'Un client demande où en est son dossier. Votre équipe doit rechercher le dernier échange et vérifier qui doit intervenir.',
 'Nous préparons des écrans et étapes adaptés à votre processus, avec les accès de votre équipe et les informations visibles au client.',
 'Un portail de suivi défini par dossier, avec statuts, documents et actions attribuées selon les rôles.',
 ['Un statut plus facile à retrouver pour chaque dossier.','Moins d’échanges uniquement destinés à demander une mise à jour.','Une séparation claire entre informations internes et suivi client.'],
 ['Un appareil est en cours de diagnostic','L’équipe met à jour le statut et les pièces utiles. Le client peut voir l’étape autorisée, tandis que les notes internes restent réservées à l’équipe.'],
 [['Décrire le parcours','Nous listons les étapes et personnes impliquées.'],['Préparer le portail','Les écrans et droits sont testés sur des exemples.'],['Valider les usages','Chaque rôle vérifie ce qu’il peut consulter et modifier.']],
 ['Vos étapes de dossier.','Les rôles et droits d’accès souhaités.','Les documents et notifications à prévoir.'],
 'Vous validez les informations visibles pour chaque rôle. Un premier prototype sert à confirmer le parcours avant exploitation.');
wf('W29',['P065'],'pilotage','Préparez les devis et notifications depuis le dossier',
 'Nous pouvons relier les informations d’un dossier à la préparation d’un devis et aux notifications utiles à votre équipe ou au client.',
 'Les informations sont recopiées dans un document de devis. Les changements de statut demandent ensuite de préparer un email séparé.',
 'Nous définissons les champs du devis et les événements qui doivent produire un document ou préparer une notification.',
 'Un devis préparé depuis les données du dossier et les messages associés aux étapes convenues.',
 ['Moins de recopie entre le dossier et le devis.','Des messages liés à une étape précise du traitement.','Une vérification plus simple des informations avant envoi.'],
 ['Le diagnostic est terminé','Les lignes prévues servent à préparer le devis. Une notification peut être déclenchée après validation. L’envoi réel doit être vérifié dans le parcours avant exploitation.'],
 [['Choisir les données','Vous définissez les champs nécessaires au devis.'],['Préparer les documents','Les informations du dossier sont reprises dans le modèle.'],['Tester les notifications','Le message et sa réception sont vérifiés.']],
 ['Votre modèle de devis.','Les données disponibles dans le dossier.','Les destinataires et moments d’envoi.'],
 'Votre équipe valide prix et devis. Paiement et livraison email sont des parcours à vérifier séparément.');
wf('W30',['P106','P075'],'experience','Proposez un canal de commande directe à vos clients',
 'Nous pouvons concevoir un parcours où votre client choisit les produits, renseigne sa commande et reçoit un suivi adapté à votre organisation.',
 'Les commandes arrivent par différents canaux. Votre équipe ressaisit les informations et confirme les disponibilités ou la livraison.',
 'Nous cadrons le catalogue, les étapes de commande et la connexion possible à vos outils de caisse ou de gestion.',
 'Un parcours de commande défini, puis un prototype pour vérifier choix des produits, réception et traitement.',
 ['Un parcours plus clair pour le client qui veut commander directement.','Des informations de commande mieux organisées.','Moins de recopie si la connexion à vos outils est disponible.'],
 ['Un client prépare une commande depuis son téléphone','Il choisit des produits disponibles et le mode prévu. Votre équipe reçoit une demande structurée et vérifie comment elle entre dans ses outils avant de confirmer le parcours.'],
 [['Cadrer la commande','Nous définissons produits, horaires et modalités.'],['Tester le parcours','Le prototype permet de vérifier les étapes avec votre équipe.'],['Vérifier les connexions','Réception, caisse et traitement sont testés avant exploitation.']],
 ['Votre catalogue et règles de commande.','Vos outils de caisse ou de gestion.','Les modalités de retrait ou de livraison.'],
 'Les intégrations et le traitement réel des commandes doivent être vérifiés avant mise en service.');
wf('W31',['P046','P075'],'experience','Retrouvez l’historique client pour préparer vos offres de fidélité',
 'Nous pouvons relier clients, commandes et avantages pour préparer des actions de fidélité adaptées à des groupes identifiables.',
 'Les commandes et contacts sont séparés. Votre équipe ne sait pas facilement quels clients sont revenus ou quels avantages ils ont déjà utilisés.',
 'Nous cadrons la correspondance entre client et historique, puis les règles d’avantage et de suivi.',
 'Une vue client et des segments utilisables pour préparer un programme ou une campagne de fidélité.',
 ['Une meilleure lecture des commandes par client.','Des avantages préparés selon des règles communes.','Une mesure prévue pour comparer les actions réellement utilisées.'],
 ['Préparer une offre pour les clients réguliers','Un segment est défini à partir de l’historique disponible. Vous choisissez l’offre et les destinataires autorisés. Le suivi distingue l’offre préparée de celle qui a réellement été utilisée.'],
 [['Relier les données','Les clients et commandes sont rapprochés.'],['Définir les avantages','Vous choisissez conditions et exclusions.'],['Suivre l’utilisation','Le parcours doit enregistrer l’usage réel de l’avantage.']],
 ['L’historique de commandes et les identifiants clients.','Les possibilités de connexion de la caisse.','Vos règles de fidélité et de contact.'],
 'Vous validez les offres et destinataires. Les effets sur le réachat se mesurent après exploitation.');
wf('W32',['P107','P075'],'experience','Aidez vos clients à préparer leur commande dans deux langues',
 'Nous pouvons préparer un assistant qui répond depuis votre menu ou catalogue et transmet la demande à votre équipe lorsqu’une décision est nécessaire.',
 'Votre équipe répond souvent aux mêmes questions sur les produits, horaires et modalités, parfois dans plusieurs langues.',
 'Nous limitons les réponses aux informations validées et préparons un passage vers votre équipe pour les demandes incertaines.',
 'Un prototype d’assistant bilingue, ses réponses autorisées et le parcours de reprise par votre équipe.',
 ['Des réponses plus accessibles aux questions courantes.','Moins de répétition pour votre équipe.','Un relais humain prévu pour les demandes qui dépassent le catalogue.'],
 ['Un client demande si un produit est disponible','L’assistant consulte la source autorisée. Si l’information n’est pas confirmée, il transmet la question à l’équipe au lieu d’inventer une disponibilité.'],
 [['Préparer les informations','Menu, horaires et règles sont validés.'],['Tester les réponses','Les questions courantes sont vérifiées dans les deux langues.'],['Organiser le relais','Votre équipe reprend les demandes incertaines.']],
 ['Votre menu ou catalogue à jour.','Les langues et questions courantes.','Le canal de reprise par votre équipe.'],
 'Les réponses reposent sur des informations validées. Les cas sensibles ou ambigus sont transmis à votre équipe.');
wf('W33',['P108','P076'],'pilotage','Retrouvez l’origine et les pièces de chaque lot',
 'Nous pouvons organiser les étapes, documents et informations d’un lot pour que votre équipe retrouve plus facilement son historique.',
 'Les pièces de collecte, production et qualité sont rangées dans différents fichiers. Reconstituer l’historique d’un lot demande plusieurs recherches.',
 'Nous cadrons un identifiant de lot et les informations à relier à chaque étape, puis préparons un prototype de suivi.',
 'Une fiche de lot avec historique, documents et points à compléter, d’abord testée avec des données de démonstration.',
 ['Un historique plus simple à consulter par lot.','Des pièces reliées aux bonnes étapes.','Les informations manquantes deviennent visibles avant une recherche urgente.'],
 ['Retrouver un document qualité lié à un lot','Vous recherchez l’identifiant du lot et consultez les pièces associées. Une pièce manquante est indiquée. Le suivi organise les documents ; il ne certifie pas leur contenu.'],
 [['Définir le lot','Nous choisissons l’identifiant et les étapes.'],['Relier les pièces','Les documents sont associés au bon lot.'],['Tester la recherche','Votre équipe vérifie qu’elle retrouve les informations nécessaires.']],
 ['Vos étapes de production et de suivi.','Les identifiants utilisés.','Les pièces et informations nécessaires aux équipes.'],
 'Vos responsables confirment les données de qualité. Le prototype ne constitue pas une certification.');
wf('W34',['P109','P076'],'commercial','Préparez les rapprochements entre lots disponibles et besoins acheteurs',
 'Nous pouvons comparer des caractéristiques de lots aux besoins déclarés par des acheteurs pour préparer une liste de pistes à vérifier commercialement.',
 'Votre équipe compare manuellement specifications, quantités et besoins acheteurs dans plusieurs tableaux.',
 'Nous rendons les critères explicites et préparons les correspondances possibles avec les informations manquantes.',
 'Une liste de rapprochements proposés, avec critères compatibles et points à confirmer.',
 ['Moins de comparaison répétitive entre offres et demandes.','Des critères lisibles pour chaque rapprochement proposé.','Des échanges commerciaux mieux préparés.'],
 ['Un acheteur cherche un lot avec des caractéristiques précises','Les lots documentés sont comparés à ses critères. Votre équipe retrouve les pistes compatibles et vérifie disponibilité, qualité et conditions avant tout engagement.'],
 [['Structurer les critères','Nous organisons les caractéristiques des lots et demandes.'],['Comparer les données','Les compatibilités connues sont repérées.'],['Préparer la vérification','Les questions ouvertes sont affichées pour le commercial.']],
 ['Les caractéristiques documentées des lots.','Les critères et besoins acheteurs.','Les règles de disponibilité et de qualification.'],
 'Votre équipe confirme les informations et les conditions. Aucune transaction n’est conclue automatiquement.');
wf('W35',['P074'],'experience','Un programme de fidélité plus facile à suivre en point de vente',
 'Nous pouvons concevoir un parcours d’identification client relié à son historique et à ses avantages, avec les accès disponibles dans votre caisse.',
 'Les membres sont reconnus de façon différente selon les équipes. Leur historique et leurs avantages sont difficiles à retrouver au comptoir.',
 'Nous cadrons l’identification, la connexion aux commandes et les règles d’utilisation des avantages.',
 'Un prototype de parcours membre, une fiche client et les règles d’avantages à tester.',
 ['Un client régulier plus facile à identifier.','Des avantages plus simples à consulter pour l’équipe.','Un parcours prévu pour suivre l’utilisation réelle.'],
 ['Un membre se présente au comptoir','Un identifiant ou un QR code permet de retrouver son profil dans le scénario proposé. L’équipe vérifie l’avantage disponible et son utilisation. La connexion à la caisse doit être confirmée.'],
 [['Choisir l’identification','Nous définissons le parcours membre.'],['Relier l’historique','Les commandes accessibles sont associées au profil.'],['Tester au comptoir','L’équipe vérifie le parcours et les cas de reprise.']],
 ['Votre caisse et ses accès disponibles.','Les règles du programme membre.','Le parcours d’identification souhaité.'],
 'Vous validez les règles et l’utilisation des données clients avant une campagne.');
wf('W36',['P074'],'experience','Préparez des offres ciblées et mesurez leur utilisation',
 'Nous pouvons relier les offres de fidélité à des segments clients et à leur utilisation en caisse pour savoir ce qui a réellement été activé.',
 'Une offre est envoyée, mais votre équipe ne sait pas clairement qui l’a utilisée ni si elle correspondait au groupe visé.',
 'Nous cadrons les groupes, conditions et identifiants d’offre, puis le suivi des usages accessibles dans vos outils.',
 'Des offres préparées par segment et un suivi de leur activation et utilisation.',
 ['Des conditions d’offre plus claires pour chaque groupe.','Une distinction entre offre envoyée et offre réellement utilisée.','Des données utiles pour décider de la prochaine campagne.'],
 ['Une offre destinée aux membres inactifs','Vous choisissez la période et le groupe. Chaque utilisation est reliée à l’offre si la caisse le permet. Votre équipe analyse les usages sans attribuer automatiquement tout le revenu à la campagne.'],
 [['Définir les groupes','Les critères et exclusions sont choisis.'],['Préparer les offres','Conditions et identifiants sont définis.'],['Suivre les usages','Le parcours en caisse est vérifié.']],
 ['L’historique client accessible.','Les conditions des offres.','Une possibilité de suivi dans la caisse.'],
 'Vous validez les groupes et contacts. Un revenu incrémental demande une méthode de mesure adaptée.');
wf('W37',['P079'],'catalogue','Préparez un catalogue e-commerce pour plusieurs langues',
 'Nous pouvons organiser produits, contenus et parcours par langue pour préparer une boutique plus facile à utiliser par vos différentes clientèles.',
 'Les textes et images sont dispersés. L’ouverture d’une langue exige de retrouver les sources et de contrôler chaque page.',
 'Nous cadrons le catalogue, les traductions et les points du parcours à vérifier avant une publication.',
 'Un plan de contenus et de parcours multilingues, puis un pilote sur une sélection de pages.',
 ['Des contenus plus cohérents entre les langues.','Une préparation structurée avant l’ouverture d’un marché.','Les points de contact et d’achat sont inclus dans la vérification.'],
 ['Préparer une deuxième langue pour une gamme','Les fiches sources sont sélectionnées et adaptées. Votre équipe vérifie descriptions, variantes et parcours de demande ou d’achat avant de publier davantage de pages.'],
 [['Organiser le catalogue','Les sources et pages utiles sont identifiées.'],['Préparer une langue pilote','Les textes et parcours sont adaptés.'],['Contrôler les pages','Le rendu et les actions attendues sont vérifiés.']],
 ['Votre catalogue et contenus de référence.','Les langues et marchés visés.','Les parcours commerciaux à vérifier.'],
 'Votre équipe valide les informations et les contenus. Les effets commerciaux se mesurent après lancement.');
wf('W38',['P110','P077'],'pilotage','Préparez vos affectations de missions avec des informations réunies',
 'Nous pouvons réunir disponibilités, critères de mission et documents pour aider votre équipe à préparer les affectations et dossiers administratifs.',
 'Les disponibilités et besoins sont éparpillés. Votre équipe compare plusieurs listes et recherche les documents avant de préparer une affectation.',
 'Nous cadrons les critères administratifs, les informations accessibles et une vue de rapprochement soumise à validation.',
 'Un prototype de suivi des missions, disponibilités et documents, avec des propositions à revoir par un responsable.',
 ['Moins de recherches entre les listes de disponibilités et missions.','Les pièces manquantes sont visibles dans le dossier.','Une préparation plus claire de la décision du responsable.'],
 ['Une mission demande plusieurs disponibilités','L’équipe consulte les disponibilités déclarées et les critères administratifs connus. Elle décide ensuite qui contacter et vérifie les conditions avant l’affectation.'],
 [['Définir les critères','Les besoins et informations nécessaires sont explicités.'],['Réunir les dossiers','Disponibilités et pièces sont regroupées.'],['Valider l’affectation','Le responsable choisit et prépare les documents.']],
 ['Les étapes administratives de vos missions.','Les disponibilités déclarées.','Les droits d’accès et documents nécessaires.'],
 'Le responsable garde le choix et la validation des affectations. Le scénario ne prend aucune décision médicale.');
wf('W39',['P078'],'experience','Repérez ce qui empêche votre site de transformer une visite en demande',
 'Nous examinons votre site comme un prospect : compréhension de l’offre, pages accessibles, contact et informations nécessaires pour décider.',
 'Vous recevez des visites, mais ne savez pas si le problème vient du message, d’une page ou du parcours de contact.',
 'Nous parcourons les pages et actions clés, documentons les problèmes observés et classons les corrections par priorité.',
 'Un audit avec exemples, problèmes observés et une liste de corrections ordonnée.',
 ['Une vision plus claire des obstacles rencontrés par le visiteur.','Des corrections priorisées plutôt qu’une liste générale de conseils.','Un point de départ concret pour améliorer le parcours commercial.'],
 ['Une offre est visible, mais son contact est difficile à trouver','L’audit relève le parcours et explique où le visiteur perd le fil. Il propose une correction ciblée. L’effet se vérifie seulement une fois la modification appliquée.'],
 [['Parcourir le site','Nous suivons les principales demandes des visiteurs.'],['Documenter les problèmes','Chaque point est relié à une page ou action observée.'],['Prioriser les corrections','Les actions sont classées selon utilité et effort.']],
 ['L’adresse du site.','Vos offres et objectifs de contact.','Les données de parcours disponibles, si vous en avez.'],
 'Vous décidez des corrections à réaliser. Un audit décrit des observations et recommandations, pas des améliorations déjà livrées.');
wf('W40',['P066'],'experience','Des pages et adresses cohérentes dans chaque langue',
 'Nous organisons les adresses et liens de vos pages multilingues pour que les visiteurs retrouvent la bonne version et le bon parcours.',
 'Une langue mène à une ancienne adresse ou une page différente. Les liens de navigation et redirections se multiplient.',
 'Nous établissons les correspondances entre pages, préparons les redirections et vérifions les principaux parcours.',
 'Une cartographie des adresses et langues, les changements prévus et un contrôle des pages concernées.',
 ['Moins de liens qui mènent à une version inattendue.','Un parcours plus cohérent lors d’un changement de langue.','Des changements d’adresse préparés avec leurs correspondances.'],
 ['Une ancienne adresse française change','La correspondance vers la nouvelle page est définie. Les liens et redirections sont vérifiés pour éviter d’envoyer le visiteur vers une page sans rapport.'],
 [['Cartographier les pages','Les anciennes et nouvelles adresses sont reliées.'],['Préparer les changements','Liens et redirections sont organisés.'],['Tester les parcours','Navigation, langues et contact sont vérifiés.']],
 ['Les adresses et langues du site.','Les changements de structure envisagés.','Les parcours commerciaux à conserver.'],
 'Les changements sont vérifiés sur les pages réellement servies avant confirmation du résultat.');
wf('W41',['P066'],'experience','Adressez chaque visiteur au bon parcours commercial',
 'Nous adaptons les appels à l’action selon le public de la page, pour qu’un particulier et un professionnel trouvent chacun la prochaine étape pertinente.',
 'Un même bouton ou formulaire est utilisé partout. Le visiteur peut tomber sur une offre professionnelle alors qu’il veut simplement acheter un produit.',
 'Nous distinguons les pages et besoins, puis relions leurs boutons aux bons parcours de demande ou d’achat.',
 'Des règles de parcours par public et des appels à l’action adaptés aux pages concernées.',
 ['Une prochaine étape cohérente avec le besoin du visiteur.','Moins de confusion entre achat particulier et demande professionnelle.','Des demandes mieux orientées vers vos équipes.'],
 ['Un particulier consulte une fiche produit','Il retrouve le parcours d’achat. Une page destinée aux professionnels peut proposer une demande de projet différente. Les deux parcours sont testés séparément.'],
 [['Identifier les publics','Les pages sont reliées à leurs besoins.'],['Adapter les actions','Les boutons et formulaires sont préparés.'],['Tester les résultats','Achat et demandes professionnelles sont vérifiés.']],
 ['Vos offres par public.','Les pages et formulaires existants.','Les actions attendues pour chaque visiteur.'],
 'Vous validez les messages et parcours. Une modification de bouton se vérifie jusqu’à l’action attendue.');
wf('W42',['P050','P067'],'catalogue','Publiez vos produits avec une préparation et une validation communes',
 'Nous réunissons préparation des données, contenus, visuels disponibles et vérification pour organiser la publication de vos produits.',
 'Une fiche est prête dans un fichier, les images dans un dossier et la validation dans un email. Votre équipe doit assembler le tout avant chaque publication.',
 'Nous préparons les éléments selon le format du site et distinguons les fiches prêtes, à compléter ou à valider.',
 'Une file de publications préparées et un suivi du résultat réellement visible sur le site.',
 ['Moins d’assemblage manuel avant de publier.','Une vue commune des fiches prêtes et des informations manquantes.','Une validation prévue avant la mise en ligne.'],
 ['Publier une nouvelle gamme','Les fiches, prix et images sont réunis. Un premier produit est publié et contrôlé sur le site. Le reste de la gamme suit après validation du parcours.'],
 [['Réunir les éléments','Données, textes et visuels sont associés au produit.'],['Préparer la publication','Les champs sont adaptés au site et soumis à validation.'],['Vérifier le résultat','La page visible est contrôlée après publication.']],
 ['Votre catalogue et ressources autorisées.','L’outil de publication utilisé.','Les personnes qui valident prix et contenus.'],
 'Votre équipe approuve les publications. Le succès sur un premier produit ne suffit pas à valider tous les produits ou sites.');
wf('W43',['P049','P067'],'catalogue','Déclinez vos contenus en plusieurs langues avec une relecture organisée',
 'Nous préparons les versions linguistiques de vos contenus et leur suivi, pour que votre équipe sache ce qui est traduit, relu et prêt à publier.',
 'Les traductions sont réparties dans des fichiers et messages. Il est difficile de savoir quelle version reprend le dernier contenu validé.',
 'Nous organisons les sources, le vocabulaire et les états de chaque langue, puis préparons une validation avant publication.',
 'Des contenus par langue avec leur état de relecture et les contrôles sur les pages publiées.',
 ['Moins de suivi manuel entre les fichiers de traduction.','Un vocabulaire plus cohérent dans les langues concernées.','Une distinction claire entre texte préparé et page vérifiée.'],
 ['Mettre à jour une description dans plusieurs langues','La version source est confirmée, puis déclinée. Chaque langue conserve un état de relecture. Les pages publiées sont contrôlées pour vérifier que la nouvelle version est visible.'],
 [['Valider la source','Le texte et les termes de référence sont confirmés.'],['Préparer les langues','Les adaptations sont regroupées et suivies.'],['Relire et contrôler','Chaque langue et page concernée est vérifiée.']],
 ['Les contenus de référence.','Les langues et termes métier.','Un circuit de relecture adapté aux marchés.'],
 'Votre équipe valide les contenus. Les informations locales et techniques nécessitent une relecture appropriée.');
wf('W44',['P068'],'experience','Préparez votre migration de site avec les pages et parcours à conserver',
 'Nous cartographions vos pages et testons une version de préparation pour organiser une migration sans perdre de vue les contenus et parcours commerciaux.',
 'Un changement d’hébergement ou de site mélange adresses, langues, formulaires et contenus. Les éléments à conserver ne sont pas tous recensés.',
 'Nous préparons les correspondances de pages, les contrôles et une version de test avant la bascule.',
 'Un plan de migration, une version de préparation testée et la liste des points à vérifier lors de la bascule.',
 ['Une préparation plus claire des pages et adresses à conserver.','Les problèmes du parcours sont recherchés avant la bascule.','Une liste de vérification pour confirmer le site après migration.'],
 ['Changer d’hébergement pour un site multilingue','Les pages et adresses sont répertoriées. La version de test est vérifiée langue par langue. La bascule et les contrôles du site public restent des étapes séparées à confirmer.'],
 [['Recenser le site','Pages, langues et actions utiles sont listées.'],['Tester la préparation','La nouvelle version est vérifiée sans basculer le site public.'],['Préparer la bascule','Les contrôles et possibilités de retour sont définis.']],
 ['L’accès autorisé au site et à sa préparation.','Les pages et langues à conserver.','Les formulaires et actions commerciales prioritaires.'],
 'La préparation ne prouve pas que la bascule finale a été réalisée. Vous validez le moment du changement.');
wf('W45',['P051','P069'],'pilotage','Faites préparer les actions répétitives, gardez les décisions importantes',
 'Nous cadrons des assistants qui préparent contenus ou actions à partir de vos consignes, avec des validations définies avant tout envoi ou publication.',
 'Votre équipe passe du temps à coordonner plusieurs outils pour préparer une même action. Les validations sont dispersées.',
 'Nous définissons ce que l’assistant peut préparer, les données autorisées et les décisions qui doivent vous être présentées.',
 'Un pilote supervisé avec une file de propositions, les validations et la trace des actions effectuées.',
 ['Moins de coordination manuelle pour préparer une action récurrente.','Des propositions réunies au même endroit pour décider.','Un contrôle explicite sur les envois et publications.'],
 ['Préparer une publication commerciale','L’assistant prépare un brouillon à partir des informations autorisées. Votre équipe voit le contenu et valide avant publication. Une erreur ou information manquante reste visible dans le suivi.'],
 [['Définir la tâche','Les actions permises et les limites sont décrites.'],['Préparer les propositions','L’assistant travaille sur un périmètre limité.'],['Valider les actions','Les décisions importantes passent par votre équipe.']],
 ['Une tâche précise et répétitive.','Les sources autorisées.','Les règles de validation et les accès nécessaires.'],
 'Les actions externes sensibles passent par les validations prévues. Le service commence par un pilote sur un périmètre limité.');
wf('W46',['P111'],'pilotage','Réunissez les tâches de réservation et de préparation des chambres',
 'Nous pouvons prototyper une vue qui relie réservations, préparation des chambres et tâches administratives pour tester l’organisation avec votre équipe.',
 'La réception et l’équipe de préparation utilisent des listes séparées. Une modification de réservation doit être répercutée à plusieurs endroits.',
 'Nous décrivons les étapes et responsabilités, puis préparons des écrans de démonstration pour vérifier la circulation des informations.',
 'Un prototype interne à tester, avec réservations de démonstration, tâches et statuts de chambre.',
 ['Une vue commune des tâches dans le scénario testé.','Des responsabilités plus faciles à lire par équipe.','Une possibilité de valider l’usage avant un projet complet.'],
 ['Une réservation change de date','Le prototype permet de montrer la réservation et les tâches de préparation associées. Votre équipe teste le parcours. Il faut ensuite vérifier les connexions aux outils réels avant exploitation.'],
 [['Décrire les rôles','Réception, préparation et gestion sont distinguées.'],['Prototyper les écrans','Des données de démonstration permettent de tester le parcours.'],['Vérifier l’intérêt','Votre équipe décide des usages à retenir.']],
 ['Votre organisation et vos outils existants.','Les événements de réservation à prendre en compte.','Les informations nécessaires à chaque équipe.'],
 'Ce scénario repose sur un prototype interne. Aucun hôtel client ni exploitation réelle n’est présenté comme acquis.');
wf('W47',['P024'],'pilotage','Sachez quelles automatisations fonctionnent et lesquelles demandent votre aide',
 'Nous préparons un suivi des traitements et des exceptions pour que votre équipe voie les résultats attendus et sache quoi faire lorsqu’un flux bloque.',
 'Une automatisation tourne en arrière-plan. Votre équipe découvre parfois qu’un fichier manque ou qu’une sortie n’a pas été mise à jour.',
 'Nous définissons les résultats à vérifier, les alertes utiles et la façon de reprendre un traitement sans refaire une action déjà effectuée.',
 'Un suivi des traitements, les exceptions à traiter et une procédure de reprise adaptée aux flux.',
 ['Moins de découverte tardive d’un traitement incomplet.','Une liste claire des exceptions à résoudre.','Une reprise préparée lorsque les fichiers ou règles changent.'],
 ['Un fournisseur change les colonnes de son fichier','Le changement est signalé et la mise à jour ambiguë est suspendue. Votre équipe sait quel flux demande une intervention avant de repartir avec un format vérifié.'],
 [['Choisir les résultats à suivre','Les sorties réellement utiles sont définies.'],['Rendre les problèmes visibles','Les erreurs et données manquantes sont signalées.'],['Organiser la reprise','Les responsabilités et actions de retour sont décrites.']],
 ['La liste des automatisations à suivre.','Les sorties et délais attendus.','Les personnes responsables des exceptions.'],
 'Les modalités de suivi et les délais de prise en charge sont convenus selon le périmètre.');
